### ISSUE TITLE
[Arma3] Rename mod folders to lowercase

### ISSUE THREAD

**Issue by dookiejones** [GameServerManagers/LinuxGSM#1041]
Please add mod rename to lower case functionality. Something like ./arma3server rename-mods 
Should find directories starting with @ and recursively rename all sub folders and files to lowercase like rename 'y/A-Z/a-z/' *

**Comment by UltimateByte** [comment]
````bash
echo "Converting uppercase folders to lowercase"
find "${folderstoconvert}" -exec readlink -e '{}' \; | rename  'y/A-Z/a-z/'
````

**Comment by cedarlug** [comment]
I'll put on my curmudgeon hat.

This is a request along support for modules, not core to LGSM.  If you go down this route, then be prepared to support even more requests for module support.

I'd like to see this tabled until Arma3 gets its act together and fixes their crap, rather than support falling back on LGSM.

Oh, apparently I was already wearing my curmudgeon hat.  Now to find my optimism glasses.

**Comment by UltimateByte** [comment]
@cedarlug Maybe a good guide would be enough.

**Comment by dookiejones** [comment]
@Cedarlug maybe a big fat WE DO NOT SUPPORT MODS warning message when running the command?

**Comment by cedarlug** [comment]
I'm just suggesting not to spend to much time on developing wiki content that would need to be maintained/updated, or script engine development that bypasses current shortcomings.  

Maybe the warning that is output should state "WE DO NOT SUPPORT MODS (AND NEITHER DOES BOHEMIA)".

**Comment by MarkL4YG** [comment]
Bohemia doesn't even really support their linux dedicated server always getting updates week(s) delayed and never fixing warnings about some own features not being ported. Logging isn't really their thing either...
