### ISSUE TITLE
Ark LSGM Will not start with ScorchedEarth_P

### ISSUE THREAD

**Issue by kuthedk** [GameServerManagers/LinuxGSM#1058]
The title of this bug says it all.

**Comment by UltimateByte** [comment]
Wow, that's a cool issue you've done there !
So kindly asked, with so much information ! So useful !

This is no bug, but (unless proven otherwise) it is just you not knowing to search on google and read our wiki, Maybe you're having trouble to read and/or write, or you're 12Yo, in that case, i apologize.

What you're asking has already has been addressed on Discord.
We discussed about it with a server owner wanting to run the mod, investigated, and found a doc after like 1 minute of googleing.
You need to run two instances of the game.
LGSM can help you with that : https://github.com/GameServerManagers/LinuxGSM/wiki/Multiple-Servers
Then you have a few config to make in order to link them. I'm pretty sure you'll be able to find what to do exactly here : http://www.google.com

Ultimately, i'll allow myself to kindly remind you that github is not twitter and is expected to be used for real dev requests with real info, research, details... 
So if your issue is more complex a truncated title that seems to translate your lack of palatability for searching and reading; and if you're just a little bit grateful for people working on LGSM for free; and if want your issue solved; feel free to comment back onto the the issue and it'll be re-opened.
 
Note: You can also redeem yourself by making a guide that we could add to the wiki. For people who read docs of course.

**Comment by kuthedk** [comment]
Well I fixed the problem by deleting the user and the user files for arkserver, remaking the user and going through the setup again. Apparently there was an issue with the first install of the LGSM. Also as much as you have blabbed on about me not doing research I looked everywhere I knew to look including the all mighty google that you said I would be able to find the answer there(it was not). Anyways, thanks for insult after insult and next time I'll just try to avoid asking help from this community and I wish you the best of luck with your server manager.

**Comment by UltimateByte** [comment]
I'm glad to see you can actually write ! Why didn't you do it in the first place ?

What you did is not asking for help. What you did is open an almost empty issue with nothing useful in it. Look at any other opened issue, and you'll see the difference. What doesn't work ? What are you trying to do  What did you try ? That's just respect and common sense.

Get more information about how support works for this project: https://github.com/GameServerManagers/LinuxGSM/wiki/Support

Anyways, i've learned from this experience, next time i need to remember to just drop this link and shut my mouth.
