### ISSUE TITLE
What is your opinion about modified game servers?

### ISSUE THREAD

**Issue by Smile42RU** [GameServerManagers/LinuxGSM#1084]
Hi.

Unturned has RocketMod, Terraria has TShock, Minecraft has a lot of versions of core. LGSM will support modified versions of game servers?

**Comment by UltimateByte** [comment]
LGSM is always happy to support mods whenever it's possible. 
However, it seems early to speak about mods when the game isn't supported yet.
I'd suggest talking about it here https://github.com/GameServerManagers/LinuxGSM/issues/740 :)

**Comment by UltimateByte** [comment]
BTW, it's been a while since we talk about supporting Sourcemod installation for loads of source games, and ULX for Garry's Mod.
I'm into way too many things these times, sadly i can't really get into coding right now, but if nobody does it in the near future, i will certainly add those two at least, because i know how those addons work already.
I think the key is to know the addon works well, in a pretty predictable way before automatically adding them.

**Comment by UltimateByte** [comment]
Working on this now
https://github.com/GameServerManagers/LinuxGSM/issues/631

I guess we will then be able to open new issues for mods to add support to.
