### ISSUE TITLE
Auto update

### ISSUE THREAD

**Issue by uGamers** [GameServerManagers/LinuxGSM#1115]
Ok so i know there a update fuction within the script but its a manually thing right? 

Is there something we can make as far as a script to check server verison with https://steamdb.info/app/4020/ or whatever steam uses to know when there an update and then if it does not match the script will do ./gmodserver sp then ./gmodserver u so it updates by itself .

Prob would need to be a cronjob set for this to work.

Or am i just dumb and not seeing this already?

**Comment by UltimateByte** [comment]
Hi,

It is already the case. If the server is started and an update check is negative, then the server won't be restarted. For that reason, you can cronjob an update check every x time.  See scheduled updates https://github.com/GameServerManagers/LinuxGSM/wiki/Update

For gmod, i personally like to have a force-update at night (5 to 6 in the morning), so that my servers are restarted and checked for updates in the same time.

**Comment by uGamers** [comment]
Well crap lol

**Comment by UltimateByte** [comment]
No problem :p 
Take some time to read this wiki, you might find some usages that you wouldn't have even think about !

**Comment by UltimateByte** [comment]
Other nice piece of material is this page which i reworked recently: https://github.com/GameServerManagers/LinuxGSM/wiki/Cronjobs

**Comment by uGamers** [comment]
Yeah just looked at that is awsome! 

This does not pertain to LGSM

Do you know the Cron job needed to reboot the whole machine daily? Say 4am.

**Comment by UltimateByte** [comment]
Reboot the whole machine daily ? Why ?! Why would one reboot a linux machine in the first place ?
I assume you can cronjob a shutdown -r -t 0, but i see no valid reason for that.
