### ISSUE TITLE
Behavior launch gmod server

### ISSUE THREAD

**Issue by alex393820** [GameServerManagers/LinuxGSM#1153]
hello I have a problem when I run my server gmod his shows me her: Information! For more information, please see https://github.com/GameServerManagers/LinuxGSM/wiki/FAQ#-fail--starting-game-server-ownership-issues-found
I must do what

**Comment by UltimateByte** [comment]
Hi,

What version is your main LGSM script ?
`cat gmodserver | grep version`

**Comment by UltimateByte** [comment]
Oh, i've been mislead by the link actually pointing to "I'm getting 404 errors when running functions" for some reason. 
Read this https://github.com/GameServerManagers/LinuxGSM/wiki/File-Ownership will help you with linux basics. I suggest reading the whole page so that you can handle ownership better in the future.

Related: https://github.com/GameServerManagers/LinuxGSM/wiki/Permissions

**Comment by UltimateByte** [comment]
By the way, github is for bug reports rather than user based issues, so if you need more help about it, please use discord or steam forums.
https://github.com/GameServerManagers/LinuxGSM/wiki/Support
