### ISSUE TITLE
CS 1.6 RCON not working

### ISSUE THREAD

**Issue by juhssi3** [GameServerManagers/LinuxGSM#1160]
when i do ./csserver dt it says rcon passwrd is for example 123 and when i try to acces the console, (i have tried many different rcon software) it says either server not responding or con_password no password set for this server. IP and ports are correct. Help pls

**Comment by cedarlug** [comment]
It sounds like:

1. Not an LGSM issue and
2. You're blocking TCP connections to the rcon port

**Comment by juhssi3** [comment]
Yes it is LGSM cs 1.6 on my vps server, and im not blocking TCP port because i can play in the server right? And ./csserver says like this:
Ports
============================================================
Change ports by editing the parameters in:
csserver
 
Useful port diagnostic command:
netstat -atunp | grep srcds_linux
 
DESCRIPTION  DIRECTION  PORT   PROTOCOL
> Game/RCON  INBOUND    27015  tcp/udp
< Client     OUTBOUND   27005  udp
 
Status: ONLINE

**Comment by cedarlug** [comment]
"... im not blocking TCP port because i can play in the server right?"
No, that is not correct.

Gameplay is UDP, rcon is TCP.   

Having the port open doesn't matter if it's blocked by a firewall or your provider.

**Comment by juhssi3** [comment]
how to see if its blocked?

**Comment by UltimateByte** [comment]
Is that you ? 
http://steamcommunity.com/groups/linuxgsm/discussions/0/312265589446574043/

"how to see if its blocked?"
Well it all depends on your configuration... Is that a home server ? Are you using a router ? Is this a VPS ? A dedicated server ? Is there any software firewall ? Is there a hardware firewall that you can configure within your customer space ?

Since you provided no relevant details, we can't answer.
https://github.com/GameServerManagers/LinuxGSM/wiki/Support

BTW, this is not an LGSM issue until proven otherwise (like a wrong syntax in config file or something), so i'll have to close it.
If you need more help, feel free to ask on the appropriate platform with enough details and we'll be glad to help.
