### ISSUE TITLE
Multiple Teamspeak Servers

### ISSUE THREAD

**Issue by R0GGER** [GameServerManagers/LinuxGSM#1170]
I want to install and run two teamspeak servers.

**Problem:**
When I start the first (s01) and then start the second (s02), only the first server is started.
But when I start S02 first and then S01, only S02 keeps running.

Both servers have different ports and paths, but are on the same user;

**Server #1**
Path: /home/teamspeak3/ts3servers/s01
servicename: TS3-01
ini: TS3-01.ini

**Server #2**
Path: /home/teamspeak3/ts3servers/s02
servicename: TS3-02
ini: TS3-02.ini

![e2ibqp](https://cloud.githubusercontent.com/assets/8298741/19971767/4ac7d01c-a1e0-11e6-8999-ecb72bb6b051.png)

What am I doing wrong? And how can I solve this issue?

**Comment by faflfama** [comment]
Do you have a licence from Teamspeak?

**Comment by UltimateByte** [comment]
+1 multiple TS3 servera require a license. Sorry buddy.

**Comment by R0GGER** [comment]
I have a 2 licenses on the same server...

**Comment by UltimateByte** [comment]
Since i only got one NPL license, i can't replicate you issue.
I see no reason why you're facing this. However, if i were you, i would use multiple users to start off, and use the default config file and servicename for both servers. Chances are if you can't run both server, it means your license is either invalid or not recognized. Ultimately, teamspeak server logs are well made. Look at serverfiles/log (or logs, can't remember for sure), and you'll probably get the reason of your server stopping.

Since it appears not to be an LGSM issue but rather a user issue, i'll close it until proven otherwise.
https://github.com/GameServerManagers/LinuxGSM/wiki/Support
