### ISSUE TITLE
[CS:GO] Multiple script crash

### ISSUE THREAD

**Issue by fearrr** [GameServerManagers/LinuxGSM#1177]
One CS:GO server drop another CS:GO server at startup.
Service name, scripts name, ports and linux users are different.  
But processes has same names "srcds_linux". 
Maybe this is the reason for crash server?

Ports: 
```
port="27015"
sourcetvport="27025"
clientport="27005"
```
```
port="27017"
sourcetvport="27027"
clientport="27007"
```

**Comment by UltimateByte** [comment]
Hi,

It seems like you followed our recommendations.
Can you please append `./csgoserver pd` on both your servers and provide the links ?

**Comment by fearrr** [comment]
@UltimateByte , sure

http://hastebin.com/zesuvodino
http://hastebin.com/esozijejeb 

Thank you for fast reaction)

http://api.steampowered.com/ISteamApps/GetServersAtAddress/v0001?addr=5.3.217.159&format=json

**Comment by UltimateByte** [comment]
Thanks

Fo FYI, the process will always be srcds_linux, that's no issue.
The only thing you would need to worry about is the servicename, if you were installing the servers into the same user. Since you got two users, you don't need to worry about it, they can both have the same csgo-server servicename.
Since you changed the servicename, make sure that you don't have a residual csgo-server servicename running under csgoserver user.

Also, have a look at this, since you got two servers running, you can do the same diagnosing process on both and compare outputs: https://github.com/GameServerManagers/LinuxGSM/wiki/Ports#diagnosing-server-accessibility

**Comment by UltimateByte** [comment]
Ultimately, make sure you have set two different GSLT.

Since this is a non-script issue but rather a user specific issue, the help will stop there on github which is made for bug report and feature requests.

If you need more help, no problem, have a look here, you'll find appropriate places and appropriate ways to ask for help: https://github.com/GameServerManagers/LinuxGSM/wiki/Support
