### ISSUE TITLE
Can't start CS:GO server

### ISSUE THREAD

**Issue by MaestroMagnifico** [GameServerManagers/LinuxGSM#1178]
I can't start CS:GO server on my Ubuntu 14.04. I did everything exactly like in guide [here](https://gameservermanagers.com/lgsm/csgoserver/). BUT before that I installed tmux 2.2 for other reason. I think default version is 1.8.

```
csgoserver@redsquadron:~$ ./csgoserver start
[ .... ] Starting csgo-server: protocol version mismatch (client 8, server 7)
lost server
[ FAIL ] Starting csgo-server: Unable to start LinuxGSM
[ FAIL ] Starting csgo-server: Unable to start LinuxGSM: Tmux error:

Command
=================================
tmux new-session -d -s "csgo-server" "./srcds_run -game csgo -usercon -strictportbind -ip 193.124.177.79 -port 27015 +clientport 27005 +tv_port 27020 +sv_setsteamaccount {censored} -tickrate 64 +map de_dust2 +servercfgfile csgo-server.cfg -maxplayers_override 10 +mapgroup random_classic +game_mode 2 +game_type 1 +host_workshop_collection  +workshop_start_map  -authkey  {censored}"

Error
=================================
protocol version mismatch (client 8, server 7)
lost server

Fix
=================================
No known fix currently. Please log an issue.
https://gameservermanagers.com/issues
```

**Comment by UltimateByte** [comment]
Your tmux installation is messed up.

> I think default version is 1.8.

That doesn't make any sense. The only distro that still uses 1.8 is like CentOS 7. Recent ubuntu with proper package repos set are not in 1.8 for sure. Tmux 1.8 is crap, nobody should use this version. 
1.9 used in Debian 8 is totally fine though.

I've seen this kind of issues before, search for tmux on github & the steam forum, you'll find it.
http://steamcommunity.com/groups/linuxgsm/discussions/0/

If you don't find the answer, then post a thread on steam forums with proper details, since this is not an LGSM issue, it has no place on github.
https://github.com/GameServerManagers/LinuxGSM/wiki/Support

**Comment by MaestroMagnifico** [comment]
Yea, it was tmux fault. I reinstalled it to 2.0 and it works now.
