### ISSUE TITLE
DST multiserver

### ISSUE THREAD

**Issue by wargamesqcf** [GameServerManagers/LinuxGSM#1188]
Can I get clearer instruction on how to do multiserver so I can have caves on my server?

Do I edit the wget cfg file I get from you or do I edit something else? I can't really find where to edit the wget file if that is the case.

https://github.com/GameServerManagers/LinuxGSM/wiki/Don%27t-Starve-Together

**Comment by marvinl97** [comment]
#1032
I created this wiki page for the dev branch because the script in the master branch is totally outdated. Sadly it isn't finished yet. There are also guides linked that aren't depending on LinuxGSM. For now you could use them until the overhaul is finally ready.


https://github.com/GameServerManagers/LinuxGSM/blob/dstserver-new/DontStarveTogether/dstserver

**Comment by dgibbs64** [comment]
@marvinl97 pop in a pull request to develop when you think its ready :)

**Comment by marvinl97** [comment]
Fixed with r161125 (9e21a76a3421ff63680781d6a4c746cb697f29a6)
The wiki page is fitting the current version now.
