### ISSUE TITLE
log files eat my HDD!!!

### ISSUE THREAD

**Issue by hitmany** [GameServerManagers/LinuxGSM#1223]
![image](https://cloud.githubusercontent.com/assets/8200058/21604917/ea6484e8-d1b6-11e6-876c-e2b4196f31e2.png)
Its under /log/script
Every day file bigger and bigger

**Comment by UltimateByte** [comment]
At first i was gonna say:
"Your probably got addons writing a whole bunch of crap to your logs.
You can lower the logdays variable into csgoserver script to cleanup logs more often or try to find a way so that your addons don't write that much crap into the console."

But in your case, it's not console logs, but script logs. 
I suspect those logs are filled up with an abusive badly set cronjob action. So watch your cronjobs carefully.
And most of all, see what's filling up those LGSM logs.
Since those files are huge, try to run the following command on any of them:
`tail -c 10000 -f YOUR-LOG.log`

**Comment by UltimateByte** [comment]
Ultimately, github is for development, so we'll come back here only if you find a bug into LGSM.
https://github.com/GameServerManagers/LinuxGSM/wiki/Support

**Comment by hitmany** [comment]
Okay, I have a lot of logs, its not problem
But files goes more and more every day
Look: 1 day 607 mb
second day 659 mb
3 day 693 mb
So looks like old day logs stored in new day. That is issue!

**Comment by dgibbs64** [comment]
can i see a sample of the log please

**Comment by UltimateByte** [comment]
Without log content, this issue is irrelevant.

**Comment by UltimateByte** [comment]
I bet on a poorly made cronjob. Closing since no feedback.
