### ISSUE TITLE
[Rust] Auto Restart

### ISSUE THREAD

**Issue by Steff00212** [GameServerManagers/LinuxGSM#1248]
Hey, is there any way to auto-restart a server with lgsm? I asked Dr. Google, he sent me here ^^ I tried to auto-restart the server with an oxide plugin, but it just stops, since there isn't any config when it sarts again. Any Idea?

**Comment by UltimateByte** [comment]
Hey.
Are you actually using LGSM ?

Here is how support goes here: https://github.com/GameServerManagers/LinuxGSM/wiki/Support
Basically: Github is used for development only. For other stuff, use discord or Steam group.

Since you asked here, I'll answer anyways.

If you need to automate stuff while using LGSM, you can program any command at any time you like using cronjobs.
https://github.com/GameServerManagers/LinuxGSM/wiki/Cronjobs
So set a cronjob to restart at any time you want, and be sure that the server will come back up with LGSM. Unless Facepunch trololol decides to break the game again with an update of course.
