### ISSUE TITLE
Organize the LGSM folder

### ISSUE THREAD

**Issue by ChaosMTA** [GameServerManagers/LinuxGSM#1263]
Can we change up the LGSM functions/ folder to be grouped a little bit cleaner?
functions/ ..
 -- fixes/
 -- command/ ..
 -- install/ ..
 -- core/ ..

etc? Would look a lot nicer than throwing it all in the functions folder.

**Comment by UltimateByte** [comment]
I'd love to since we're beginning to have loads and loads of functions.
Such a change would require some work on how functions get downloaded though. Maybe even an entire rework. 

Ultimately I'd love to have all game scripts into /games rather than one directory per game.

In the end, there would be
lgsm.sh
games/*gamename*
functions/category/*func_name.*

**Comment by dgibbs64** [comment]
I agree with this. However as @UltimateByte says it would require a large change to the base code and although would be easier on the eyes would take a lot of time to implement. So this would not be a priority but something that would be nice to implament

**Comment by dgibbs64** [comment]
as a compromise all the functions are grouped in to several categories and are named with this category. e.g check_xx fix_xx info_xx and so on.
