### ISSUE TITLE
[RUST] Server Start Issue. "Unable to start rust-server: Tmux error:"

### ISSUE THREAD

**Issue by Nobbyblue** [GameServerManagers/LinuxGSM#1266]
**Game:** Rust.
**./rustserver postdetails :** https://hastebin.com/melibojawe
**Log (I don't think it's that useful):** http://pastebin.com/xBD3mfPk
**Linux Distro and Version:** Centos 7
**Other:** I noticed some other posts regarding a Tmux error with very similar error messages, they had responses regarding Tmux generally in their systems. I can tell you that I had LGSM Arma 3 running perfectly fine on this same system using Tmux if that's useful in any way.

To add onto that originally it gave me a 'fix' which was "usermod -G tty rustserver", I performed this fix and got identical results.

If any further information is required, I'll provide anything else I can.

**Comment by UltimateByte** [comment]
Hey. 
Thumbs up for reading our "Support" wiki page ;)

"Tmux error:" > Is this the full message?

I believe it could falsely be a tmux error.

"+rcon.password "CHANGE_ME"" >

**Comment by Nobbyblue** [comment]
Hello, thanks for your response.

Weirdly enough I am no longer getting that error. Now when I use "./rustserver start" it appears to start properly, however, the server never actually starts. Upon trying to connect through direct connect I get a connection failed error and when I use the command "./rustserve stop" it says that the server is already stopped. I've also changed the RCON password as suggested. I have made no changes what so ever since I received the initial error and the box has not gone offline so this different result is especially weird to me.

**./rustserver debug results**
[ INFO ] Debug rust-server: Stopping any running servers
[ INFO ] Stopping rust-server: rust-server - UP Test Server is already stopped
[  OK  ] Debug rust-server: Starting debug
/home/rustserver/lgsm/functions/command_debug.sh: line 107: 19162 Aborted                 ${executable} ${parms}

Pardon my ignorance, but from what I can tell a debug file hasn't been created due to an error on line 107.

No game logs were created when I was receiving the TMUX error warning, however, now I'm getting some with this issue.

**GameLog Paste:**  http://pastebin.com/81zvf9uT

**Comment by UltimateByte** [comment]
Looks like you got a residual process in the background. 
`ps aux | grep Rust` will tell you that.
Kill it (with fire... or rather with `kill {appid}` command) if needed.

I can see you updated your tmux. In some cases with CentOS, the update is partly made and you got one more step to do so that there is not a version conflict. @cedarlug knows more than i do about this, but if you're patient enough you can find back the process of diagnosing and solving this by searching here. http://steamcommunity.com/groups/linuxgsm/discussions/0/

**Comment by cedarlug** [comment]
@Nobbyblue It looks like you have a lot of "could be's" going on related to other threads.

Could be that `/sys/class/net` isn't readable. Why that matters is a mystery on par with why people park on driveways and drive on parkways.  Reference [this discussion regarding similar output](http://steamcommunity.com/groups/linuxgsm/discussions/0/154645427520545953/#c154645497345689334), try this first (as root):
```bash
chmod a+x /sys 
chmod a+rx /sys/class 
chmod a+r /sys/class/net
```
Start it up.  If it stays running your bug is due to `/sys/class/net not being readable.`  That's the quick fix.

If it doesn't run, then it might be that you're running an OVH kernel (based on the version of the kernel in your post details output).  Why that matters is a mystery on par with why Unix programmers dislike certain letters such as the `e` missing from `resolv.conf` and the `n` missing in `umount`.  You might have been bitten by the recent [issues revolving around their specific kernel](https://github.com/GameServerManagers/LinuxGSM/issues/1254).  Try upgrading to their latest experimental kernel as described in the the OVH howto (linked in the git discussion).

**Comment by cedarlug** [comment]
Re-open if the issue hasn't been solved.
