### ISSUE TITLE
Config Reset

### ISSUE THREAD

**Issue by CamaroKing59** [GameServerManagers/LinuxGSM#1278]
i am using the ark server files that is you guys have but i cant change any config they keep going to default instead of using the GameUserSetting.ini file i edit it just deletes it self and puts in a fresh one so if anyone can help please that would be greatly appreciated

**Comment by UltimateByte** [comment]
1) I already answered you on Discord, didn't I?
2) Shutdown the Ark server before editing the config
3) Edit config file with nano or vi, not with notepad++
4) Make sure there is no syntax error, otherwise, it will for sure be overwritten.
5) Github is a place for development, not solving user customization issues. https://github.com/GameServerManagers/LinuxGSM/wiki/Support
