### ISSUE TITLE
[Server Request] Tower Unite

### ISSUE THREAD

**Issue by rogeraabbccdd** [GameServerManagers/LinuxGSM#1289]
PLAY, CREATE, PARTY! Tower Unite is a community-based virtual world party game with online games, entertainment, activities, and no microtransactions.

Game
http://store.steampowered.com/app/394690
https://steamdb.info/app/394690

Dedicated Server
http://store.steampowered.com/app/439660
https://steamdb.info/app/439660/

Dedicated Server Setup Guide
http://steamcommunity.com/sharedfiles/filedetails/?id=662378924

**Comment by dgibbs64** [comment]
Looks like a fun game. Something we can look in to creating. As always if there is anyone who wants to have a go creating this feel free.

**Comment by marvinl97** [comment]
Branch: [/feature/tuserver](https://github.com/GameServerManagers/LinuxGSM/tree/feature/tuserver)

I think the implementation is almost done. I just need someone who could do the dependency stuff for me. I don't much about it. Did I miss anything else?
Output of the deps commands on Ubuntu 16.04.1 LTS x64: https://hastebin.com/cudicosiba.rb

The [config](https://github.com/GameServerManagers/Game-Server-Configs/blob/master/TowerUnite/TowerServer.ini) isn't that extensive yet because there isn't a good documentation. So I don't know if there are other settings. I messaged the devs but I didn't get an answer.

**Comment by dgibbs64** [comment]
This is a very useful tool http://packages.ubuntu.com/

That and ```yum whatprovides <file>```

Good work!!!

**Comment by rogeraabbccdd** [comment]
@marvinl97 I tried it and it worked like a charm. Thank you very much!

**Comment by dgibbs64** [comment]
Now released
