### ISSUE TITLE
version and new functions-version

### ISSUE THREAD

**Issue by dgibbs64** [GameServerManagers/LinuxGSM#1325]
I am going to look at adding a new functions version for details as the version only really represents the main script file. Whereas we have no idea the functions version in details currently. I will probably add this for core_functions.sh

**Comment by jaredballou** [comment]
The way I handled this in my branch was to query the GitHub API for the current checksums of the files in lgsm/functions for the given repo/branch and then check the local files. I had to have Git installed to do it easily, since Git hashes files in a strange way. I can dig up the code and send a PR if it'd be helpful.

**Comment by dgibbs64** [comment]
With new update system being put in place this is no longer required
