### ISSUE TITLE
Rust Server - Wipe Function

### ISSUE THREAD

**Issue by ESoTeRiC60** [GameServerManagers/LinuxGSM#1353]
Hello !

Thanks for the wipe function in LinuxGSM for RUST, but i have one question.

How to realise a wipe in crontab with the command ? Because the scripts ask for an confirmation to realise the wipe.

Thanks in advance.

Best regards

**Comment by UltimateByte** [comment]
Hey there.

You're welcome.

It asks for confirmation because this command shouldn't be ran by mistake.
It seems that it cannot really be automated after a successful update, since you should only wipe after a major update, and LGSM can't know if the last update was major or not, so it's up to user's discretion to chose if he wants to wipe or not.
As for a wipe cronjob, we can't really know for sure when Rust updates are released, so it seems unlikely to be a good idea. Same goes for Oxide that should be updated once the release is out, which happens hours after game updates, so there is no way to really plan this, it has to be "manual" (even though LGSM now simplifies the process a lot already).

If you still want to automate a wipe after considering this, tell me, and i'll try to find a workaround for you. I know @cedarlug had a nice one but I couldn't find it back.

**Comment by ESoTeRiC60** [comment]
Thanks for the answer :)

I think i found a better way to do this.

Best regards

**Comment by kossamuno** [comment]
I would like to know how you solved it, can you sharw @escoteric60 ?

**Comment by arebokert** [comment]
If anybody else stumbles across this issue, I added a workaround to the [wiki.](https://github.com/GameServerManagers/LinuxGSM/wiki/Rust)
