### ISSUE TITLE
CSGO Server: Unable to start LinuxGSM: Tmux Error

### ISSUE THREAD

**Issue by ExodusAU** [GameServerManagers/LinuxGSM#1363]
Hi, 

I am running ubuntu server 14.04 LTS and have just setup a csgo server.

Initially i was having some permission issues due to ftp over root. Fixed this and launched the server. the first error i got was pretty straight forward where i had to add my user to the group for tty.. so i did sudo usermod -G tty csgosurf.

Now i run the server again and i get the following:
[ FAIL ] Starting csgo-server: Unable to start LinuxGSM
[ FAIL ] Starting csgo-server: Unable to start LinuxGSM: Tmux error:

Command
=================================
tmux new-session -d -s "csgo-server" "./srcds_run -game csgo -usercon -strictportbind -ip 202.130.46.72 -port 27015 +clientport 27005 +tv_port 27020 +sv_setsteamaccount 377413B3792D43C0EDD67DC81A401A3D -tickrate 128 +map surf_kitsune +servercfgfile csgo-server.cfg -maxplayers_override 12 +mapgroup mg_active +game_mode 0 +game_type 0 +host_workshop_collection  +workshop_start_map  -authkey "

Error
=================================
create session failed: ./srcds_run -game csgo -usercon -strictportbind -ip 202.130.46.72 -port 27015 +clientport 27005 +tv_port 27020 +sv_setsteamaccount 377413B3792D43C0EDD67DC81A401A3D -tickrate 128 +map surf_kitsune +servercfgfile csgo-server.cfg -maxplayers_override 12 +mapgroup mg_active +game_mode 0 +game_type 0 +host_workshop_collection  +workshop_start_map  -authkey : No such file or directory

Fix
=================================
No known fix currently. Please log an issue.
https://gameservermanagers.com/issues

**Comment by UltimateByte** [comment]
Well, at least, you provided enough details so that I know you're a total newbie.
There is no issue with being  a newbie... But at least, when you got something like a permission error with a documentation link, read read it. 
https://github.com/GameServerManagers/LinuxGSM/wiki/File-Ownership
Unless of course you don't even know how to copy text from the console (just select it in putty, and it's copied into your clipboard). 

Now that you made your GSLT key public and sent it by email to hundreds of users creating this issue, you shall revoke it and make a new one. http://steamcommunity.com/dev/managegameservers

I know that the error message told you to just log an issue here, but the target link should be this one:  https://github.com/GameServerManagers/LinuxGSM/wiki/Support 
There are rules to follow before posting.

**Comment by UltimateByte** [comment]
While I'm at it: 
https://github.com/GameServerManagers/LinuxGSM/wiki/FTP-SCP
https://github.com/GameServerManagers/LinuxGSM/wiki/FTP-SCP#bad-practice-to-avoid

**Comment by ExodusAU** [comment]
Thanks for the reply, even though your responses were quite derogatory. I read all links you provided with no help at all.
you mentioned going to the overall support page prior to posting and nothing on there is of any use for this issues (that i can find) making me much more confident that this was posted correctly.

This does not seem to be just a permission issue, i had thought and checked the ownership and permissions prior to posting.. 

I have not FTP'd with root creating root ownership files, hence why i created a separate user to manage this. The user in question 'csgosurf' is the owner of all files and folders, i ran the commands you as written from the link you provided on file-ownership page.

**Comment by UltimateByte** [comment]
I can get salty when the second thing of the day that I read is 

> "i was having some permission issues due to ftp over root".

> "you mentioned going to the overall support page prior to posting and nothing on there is of any use for this issues (that i can find) making me much more confident that this was posted correctly."

Well, go read it again, because we obviously miss any relevant info that would allow to help you. Starting with `postdetails` output, then logs output, what you tried, debug start result, etc.
https://github.com/GameServerManagers/LinuxGSM/wiki/Support

Also, make sure you're following this general guidance to solve issues https://github.com/GameServerManagers/LinuxGSM/wiki/Troubleshooting

**Comment by ExodusAU** [comment]
As i mentioned in my first post, I was having issues with root over ftp. realised that was a problem and rectified it to ensure that wasn't causing the issue. then your response is to check that when i clearly stated it wasnt.

yes i am a noob to this, but providing links with no direction is a poor way to assist somebody who is asking for help. if it is too difficult for you to provide some real insight then please move on.

I will persist on my own or will try elsewhere.

**Comment by UltimateByte** [comment]
The support link tells you what we need to know in order to be able to help.
"I HAZ EROR PLIZ FIX" is not a way to ask for support in a Linux environment, we need real details.
Connect to FTP using root: Get salt. 
No `postdetails` output, no logs output, nothing about what you tried to diagnose the issue, not following usual guidance on how to solve issues: Then yeah, make me a favor: Go try elsewhere.

**Comment by marvinl97** [comment]
@ExodusAU It's much easier and more comfortable for us to post links in these issue threads so we don't have to copy and paste it a thousand times... The wiki isn't there just for fun. I think that it's friendly structured and contains many useful information.

**Comment by ExodusAU** [comment]
@marvinl97 I totally understand the underlying message, yes i did just ready the message saying to come and post here and it would have been better to provide a link direct to the wiki.

However, rather than someone being an arrogant a$$ in their response. why not be helpful and respond with something less rude such as: Hi, the link it should have provided was to the wiki *url*. So that we can assist with your problem a good first step would be to have a read of that as well as provide us with the output from executing the command ./gameserver postdetails.

thats it, simple. no need to be rude. So i would rather not pursue this further with someone who doesnt seem capable of working with new comers.

**Comment by UltimateByte** [comment]
> I know that the error message told you to just log an issue here, but the target link should be this one: https://github.com/GameServerManagers/LinuxGSM/wiki/Support
> There are rules to follow before posting.

I informed you kindly. You ignored this part.

**Comment by JimTR** [comment]
my point exactly .. cs is lacking
