### ISSUE TITLE
[SERVER REQUEST] Dayz Mod

### ISSUE THREAD

**Issue by nadal28** [GameServerManagers/LinuxGSM#1373]
The first of many other survival games, this is a mod of Arma 2 Operation Arrowhead, many mods added to dayz mod like dayz mod epoch, dayz mod origins...

I it saw here: https://github.com/emestee/dayz-epoch-linux-server-magic there is some job done, it would be could to see it inside LinuxGSM

**Comment by SkullMasher** [comment]
> Wine is not required.
https://github.com/emestee/dayz-epoch-linux-server-magic#what-is-this
Great ! I forgot DayZ existed, standalone game still in early access.

**Comment by nadal28** [comment]
@SkullMasher But the game I posted is Dayz Mod, an arma 2 mod, not dayz standalone.

**Comment by SkullMasher** [comment]
@nadal28 Yes I know but still, DayZ standalone is so slow to come...

**Comment by marvinlehmann** [comment]
I don't see it coming because this would be only a really outdated version a non-vanilla DayZ, Epoch.
As far as I know it's only so problematic because of the missing support for loading shared libraries (.so files). So the hive (https://github.com/rajkosto/hive) can't be used, even if it would have been converted to Linux.

As a workaround you would have to write a hive-like implementation yourself like https://github.com/denisio/Dayz-Linux-Server/blob/master/writer.pl . But you also have to edit the server/mod files too (change all the hive calls and so on). It's tons of work and would require manual updates. :/

**Comment by nadal28** [comment]
I want to create a private hive, like most of epoch servers, also I want to work only over 1.0.5.1 epoch version, I really hate the new 1.0.6 version xD

Im bored and Im going to try this in a virtual box :P

**Comment by dgibbs64** [comment]
Placing in "waiting response" will close after 30 days. Doesn't looks like DayZ is feasible
