### ISSUE TITLE
grep broken pipe on server install

### ISSUE THREAD

**Issue by ProjectPatatoe** [GameServerManagers/LinuxGSM#1453]
while installing both CS:GO and CS1.6 I get this during install
```
Downloading Counter-Strike 1.6 Config
=================================
default configs from https://github.com/GameServerManagers/Game-Server-Configs
mkdir: created directory '/home/gameds/cs/lgsm/default-configs'
    fetching server.cfg...OK
copying server.cfg config file.
'/home/gameds/cs/lgsm/default-configs/server.cfg' -> '/home/gameds/cs/serverfiles/cstrike/cs-server.cfg'
grep: write error: Broken pipe

```
and then nothing happens
I am running under the user "gameds" and it does have the permissions to 'rwx' in this folder. For the time being, my csgo server I manually edited my server config files because I needed it running at the time. But since, don't need 1.6 running yet I would like to figure out this bug/issue. Running `Ubuntu 16.04.2 LTS (GNU/Linux 4.4.0-78-generic x86_64)`

**Comment by UltimateByte** [comment]
Please, postdetails as per https://github.com/GameServerManagers/LinuxGSM/wiki/Support
I've seen this before, can't remember why. There is most likely something with the way your distro handles grep, or a syntax error due to a var not expressing properly.
Can you try to provide info about your grep ?
like outputs from:
which grep
grep --version (not sure of this one exists though)
Also, run ./gameserver dev, make the issue occur, then provide the .dev-debug.log output using pastebin or equivalent.
Those things would help diagnosing this.

**Comment by ProjectPatatoe** [comment]
postdetails: [postdetails - hastebin](https://hastebin.com/examaqanix)
grep: `grep (GNU grep) 2.25`
dev-debug.log: [hastebin](https://hastebin.com/xiruyixolo)

**Comment by UltimateByte** [comment]
Thanks.
You got an issue with random password generation.
That allowed me to find the issue where it is discussed already.
https://github.com/GameServerManagers/LinuxGSM/issues/1308
Closing this one, and will try to boost the fix from the other issue.
