### ISSUE TITLE
7DTD - not installing latest_experimental

### ISSUE THREAD

**Issue by Maygus** [GameServerManagers/LinuxGSM#1470]
https://hastebin.com/esaxujavas

I've gone through it a few times, re-installed completely including using the develop branch.
I cannot get the server to install the latest_experimental build no matter what I try.

Alpha 16 was released 4 days ago and each time it is install the stable version which is Alpha 15

```
[  OK  ] Update sdtd-server: Checking for update: SteamCMD: No update available

No update available:
        Current version: 1642899
        Available version: 1642899
        https://steamdb.info/app/294420/

```

I have even tried with -beta latest_experimental with the same result.

**Comment by Maygus** [comment]
if I do a force-update it pulls it down, but now fails to launch with no error. Seperate game server issue I imagine I'll have to resolve.

**Comment by Khelgar1** [comment]
Try this 
`rm -R serverfiles/
cd steamcmd
./steamcmd.sh
login username pass
force_install_dir ../serverfiles
app_update 294420 -beta latest_experimental validate
quit`

Then copy the default serverconfig.xml to sdtd-server.xml and it should work. lgsm pulls down an old version of the xml which prevents the server from starting

**Comment by Maygus** [comment]
Yeah - I changed one variable but didn't remove the enemysense variable in the XML.

Was just frustrating trying to get the server down at least a force-update works to pull the experimental down.

**Comment by maisn** [comment]
Same Problem - My Fix was:
In the File https://github.com/GameServerManagers/LinuxGSM/blob/master/lgsm/functions/update_steamcmd.sh
("directory in is your sdtdserver file"/lgsm/functions/update_steamcmd.sh)

i changed the line no 168 from
"availablebuild=$(./steamcmd.sh +login "${steamuser}" "${steampass}" +app_info_update 1 +app_info_print "${appid}" +app_info_print "${appid}" +quit | sed -n '/branch/,$p' | grep -m 1 buildid | tr -cd '[:digit:]')"

to
"availablebuild=$(./steamcmd.sh +login "${steamuser}" "${steampass}" +app_info_update 1 +app_info_print "${appid}" +quit | sed -n '/branches/,$p' | sed -n "/$branchname/,\$p" | grep -m 1 buildid | tr -cd '[:digit:]')"

and finally it works.

Please: This is a fix for me and my system (debian 8.8 jessie) - not an official! I give no guarantee that this fix helps on other system or didn't broke some different functions! When anyone use this fix its his own fault :)

Note: In the 'sdtdserver' file you must write "-beta latest_experimental" in the "branch" variable. Only a "latest_experimental" do not change anything because the script needs more than one argument.

**Comment by UltimateByte** [comment]
I have just tried installing the latest Beta, worked fine 1st attempt.

I had deleted the current version by removing serverfiles first, but any issue that might be caused by not doing that is due to either steamcmd or user.

I would say the issue isn't an issue anymore.

**Comment by ColderCoder** [comment]
I'm upgrading A18.4 stable to A19 experienmental. 
I cleared everything in folder **/serverfiles**, used steamcmd to download the latest_experimental version and moved them to **/serverfiles**. Here's the output as I run **./sdtdserver m**:

> [ INFO ] Monitor sdtdserver: Check IP: (my ip)
> [  OK  ] Monitor sdtdserver: Checking session: OK
> [ FAIL ] Monitor sdtdserver: Querying port: gsquery: (my ip):2690026900269052701527020

It's just wried. I left everything default and the port should be 26900 instead of 2690026900269052701527020.
(i'm sorry for popping up an old thread)
