### ISSUE TITLE
config confusion 

### ISSUE THREAD

**Issue by SB97** [GameServerManagers/LinuxGSM#1564]
after installing my gmod server i  found out that `./gmodserver dt` shows `Config file:         /home/gmodserver/serverfiles/garrysmod/cfg/gmodserver.cfg` but there are also configs in `/lgsm/config-lgsm/gmodserver`. The detail page also says `Change ports by editing the parameters in:
gmodserver`

the wiki states that [https://github.com/GameServerManagers/LinuxGSM/wiki/LinuxGSM-Config-Files](url) config-lgsm files are the right one.

I found the same problem with my ark server so i guess it is a general issue?

I think the wiki is right and the detail page should show the location for the configs to edit

**Comment by MarkL4YG** [comment]
The config files in ``config-lgsm`` are for general things needed by lgsm: server parameters, directories and stuff. The config in your "cfg" directory is used by the gmod server and contains gamemode settings, map settings etc.

**Comment by PhilippLoewen** [comment]
As far as I understand you should not edit the script itself anymore. This should was apparently necessary in older versions (before June). The documentation  isn't completely up to date yet.

**Comment by Okonos** [comment]
I also struggled with svenserver configuration file location.
`./svenserver details` shows:
`Config file:            /home/svenserver/serverfiles/svencoop/svenserver.cfg`,
while the real config file taking effect turns out to be `server.cfg` in the same directory.
Actually the whole "Server Details" section returns wrong information. Pretty misleading.

**Comment by dgibbs64** [comment]
@Okonos svenserver.cfg should be the correct config file. Unless sven co-op does it different to every of gold source game

Also the documentation should now be up to date

**Comment by dgibbs64** [comment]
Is there anything more required from this? Will close in 30 days if no respons

**Comment by UltimateByte** [comment]
User just struggled understanding new LinuxGSM config system because the details page was displaying incorrect information: Was saying to edit "gameserver" script instead of the config file, which is now resolved.

Example:
`Config file:            /home/ultimatebyte/serverfiles/server.properties`

Also, now the doc should be good enough to cover this kind of questions.
https://github.com/GameServerManagers/LinuxGSM/wiki/LinuxGSM-Config
https://github.com/GameServerManagers/LinuxGSM/wiki/Game-Server-Config
