### ISSUE TITLE
[Compatibility Checks] Submit Distro Checks

### ISSUE THREAD

**Issue by dgibbs64** [GameServerManagers/LinuxGSM#157]
# Want to help with the LGSM project?

Simply install and confirm that a game server works with a your Distro. 

There are around 25 different game servers supported and has now become impossible for me to test on all distros and versions. 

If you have run a game server on a distro that has not been tested let me know the results. I will add it to a spreadsheet for all to see so we know that the server does work with a particular distro. Making it easy to know what works and what does not.

Currently I have Ubuntu, Debian and CentOS on the spreadsheet. However if you have another distro you use I am happy to add it on if the results are provided.

Below is a spreadsheet of all results and when it was tested.

http://danielgibbs.co.uk/lgsm-compatabillity

Submit your results below using the template and I will update the spreadsheet.

**Server Name:**
**Pass/Fail:**
**Distro:**
**Version:**
**Architecture:**
**Dependencies:**
**Extra Notes:**

Further notes:
I normaly check dependencies myself. However if there is something missing please add details. 

 SteamCMD is only compatible with systems that support 32-Bit architecture.

**Comment by BlueToxic** [comment]
<b>Server Name:</b> Counter-Strike: Global Offensive
<b>Pass/Fail:</b> Pass
<b>Distro:</b> Amazon Linux AMI
<b>Version:</b> 2014.09.1 (http://aws.amazon.com/amazon-linux-ami/2014.09-release-notes/)
<b>Architecture:</b> x64
<b>Dependencies:</b> As the guide + <code>libgcc48.i686</code>
<b>Extra Notes:</b>

I got the following error when trying to install the server using only the dependencies in the guide:
```
error while loading shared libraries: libgcc_s.so.1: cannot open shared object file: No such file or directory
```

After some searching I found out that I was missing the package <code>libgcc48.i686</code>. After installing that package the installation went through without errors. This package depends on glibc.i686 so using ```yum install tmux gdb mailx postfix libgcc48.i686``` is enough.

I guess it didn't automatically install <code>libgcc48.i686</code> because <code>glibc.i686</code> has several providers for <code>libgcc</code> (see below) and <code>libgcc48.x86_64</code> was already installed.
From glibc.i686's deplist:
```
  dependency: libgcc
   provider: libgcc48.x86_64 4.8.2-16.2.99.amzn1
   provider: libgcc48.i686 4.8.2-16.2.99.amzn1
   provider: libgcc44.x86_64 4.4.6-4.81.amzn1
   provider: libgcc44.i686 4.4.6-4.81.amzn1
```
Not sure if it's something unique for Amazons distro but looks like they added the version number in the package name so "48" will probably be another number if the package is upgraded.
