### ISSUE TITLE
CS:GO Fast DL

### ISSUE THREAD

**Issue by IvanIsAGod** [GameServerManagers/LinuxGSM#1585]
I might found a bug in the LGSM script. I typed ./csgoserver fastdl and something crazy happened. It creates the normal "public_html" folder and the under folders like "models, materials etc". But all materials that i have on the server will be packed into bzip2 (normal) and will be placed in the "materials" folder. Example: csgo/materials/zombie.vtf ! cstrike/materials/skelleton.vtf. But on my server its like this: csgo/materials/models/player/zh/zombie.vtf.  It means the command with "fastdl" dont put the materials and models in the right folder. (I hope you understand what i am writing. My english is terrible)

directory structure is not correctly converting over to the fastdl dir.
Server: csgo/materials/models/player/zh/zombie.vtf
FastDL: csgo/materials/skelleton.vtf.bz2

**Comment by UltimateByte** [comment]
This is the expected behavior for any source except for gmodserver and should be OK for css or csgo.
This was discussed with @dgibbs64 upon FastDL script's creation.

**Comment by JimTR** [comment]
glad you got that far all I see is
`gathering *.vmt : 57.../home/tracey/games/gmod/lgsm/functions/command_fastdl.sh: line 165: /fastdl_files_to_compress.txt: Permission denied`

**Comment by MarkL4YG** [comment]
@JimTR if you mean you also got problems - that error message is unrelated to this issue and just tells us your folder/file permissions are not set up properly.

**Comment by JimTR** [comment]
Ok what users/groups do I need to set to as currently the accessible domain has a different user to the game server
1 Game Sever Owner = Game Name
2 Web domain  = www-data 
but I would guess /fastdl_files_to_compress.txt applies to the root directory and to be fair I would not allow www-data/game server owner read write access to the root ... perhaps this needs to be in the home directory e.g /home/<username>/<whatever> rather than root ?

**Comment by UltimateByte** [comment]
I cannot see a reason why being in root dir would be an issue. Though your issue is a different one @JimTR 
You can open your own issue with relevant details if you think that is something that LGSM could fix.

**Comment by UltimateByte** [comment]
As for the initial issue, @NoodlesCG > Did you actually try using it this way ? Didn't you get clients to download these files ? If not, did you not at least get clients to download files in the "right" directories ?

Because unless proven otherwise, I assume the generator works as it should, but your FastDL share isn't working and you should double check the share and cfg file in the first place.

**Comment by NoodlesCG** [comment]
@UltimateByte I did yes and in console I would check and just see error downloading. Only some models and all maps ended up being downloaded because those were in the root folder of "models".

**Comment by xxngle** [comment]
1 year passed :<

**Comment by Larsalex1337** [comment]
fix plz

**Comment by h3o66** [comment]
if i am not wrong this is connected to #2437 and the pulll #2450 should fix this

would be good if somebody could test this and confirm
