### ISSUE TITLE
FastDL

### ISSUE THREAD

**Issue by JimTR** [GameServerManagers/LinuxGSM#1591]
Ok We are running a server and require fast DL .. all looks good until you have multiple domains on the same server .. for security you would never allow a user to have write access to the root directory as this may allow the user access to parts of the OS that they should not have access to. Taking into account you have coded this assuming that the user has root access .. when a user is not root it just fails and the file should be located in a place that the user can access. If the server has more than 1 web user (not just the default) LSGM should respect that ... that said if you don't want to support web servers that have more than one web user please ignore this

**Comment by popey456963** [comment]
As far as I know, LGSM creates it's own directory in the csgoserver file directory & then expects a user to symbolically link to that location.

I _believe_ this gets around the security issues you're talking about?

**Comment by UltimateByte** [comment]
LGSM cannot be run as root, so using LGSM, users write fastdl dirs into their own directory, then the web server can read files from the user with the default umask. For simplicity, it is expected that the sysadmin uses userdir mod from Apache.
https://github.com/GameServerManagers/LinuxGSM/wiki/FastDL

If there is anything we can adjust to keep it this way while pleasing you, don't hesitate to mention it. Otherwise, we can just close the issue.
