### ISSUE TITLE
Give an option to omit -ip start param

### ISSUE THREAD

**Issue by marlonrichert** [GameServerManagers/LinuxGSM#1593]
Because if you run a Steam Source server (for example, TF2) with the -ip (or +ip) param, it will not show up in the LAN browser on the client: http://www.fusionnetwork.us/index.php/articles/general-tutorials/steam-fix-lan-server-not-showing-up-in-lan-server-browser/

**Comment by UltimateByte** [comment]
You can remove the start parameter manually into your lgsm config file.

**Comment by marlonrichert** [comment]
@UltimateByte, in `_default.cfg`, there is `ip="0.0.0.0"`, which is passed to Source's `-ip` param (where LGSM automagically replaces `0.0.0.0` with you actual IP address). The only way I see to remove the `-ip` param is override the entirety of this:

```
fn_parms(){
parms="-game tf -strictportbind -ip ${ip} -port ${port} +clientport ${clientport} +tv_port ${sourcetvport} +map ${defaultmap} +sv_setsteamaccount ${gslt} +servercfgfile ${servercfg} -maxplayers ${maxplayers}"
}
```

Yes, that works, but if I override that entire thing there, I will also automatically be overriding any future updates to that construct. I would like there to be an easier way that is more forward compatible.

**Comment by UltimateByte** [comment]
This is because _default.cfg is default, therefore you cannot edit it directly. You need to pass parameters from this file to your instance config file, as per documentation.
https://github.com/GameServerManagers/LinuxGSM/wiki/LinuxGSM-Config-Files#how-to-get-started-with-the-new-config-files-system

**Comment by marlonrichert** [comment]
Yes, in `tf2server.cfg`, I am overriding `fn_parms(){ parms="…" }`. That means, however, that if `fn_parms(){ parms="…" }` gets updated somehow in `defaults.cfg`, I will not get any of those changes on my server. I mean, I am this way overriding _all_ start params, when I only want to remove the `-ip` param specifically. If later any start params in `_default.cfg` are added or removed, those changes will no longer cascade to me.

Or am I missing something here? Is there some way in which I can remove the `-ip` param in `tf2server.cfg` without overriding that `fn_parms(){ parms="…" }` construct?

**Comment by jimwald1221** [comment]
There isn't a logical way since the scripts pull from the custom configuration then from the default. If the flags exist in the custom config then they are ignored in the `_default.cfg` in their entirety.

IMO, you probably shouldn't rely on the default string to run things if you want it to be consistent anyway. If you want to research the flags of it, you should check out the [other command line options](https://wiki.teamfortress.com/wiki/Linux_dedicated_server#Create_a_shell_script_to_run_the_server) from the wiki.

**Comment by jimwald1221** [comment]
I also wonder if your server is meant to be internet facing? If so, clients should be able to use whatever external IP or dynamic DNS name given to find and connect as well as use the local IP of the host machine and add the server to their favorites if it's LAN only.

**Comment by jimwald1221** [comment]
I also wonder if your server is meant to be internet facing? If so, clients should be able to use whatever external IP or dynamic DNS name given to find and connect as well as use the local IP of the host machine and add the server to their favorites if it's LAN only.

**Comment by dgibbs64** [comment]
Removing the -ip from the parms is the best way. parms rarely get updated so I wouldnt worry at all.
