### ISSUE TITLE
Make `reload` an alias of `restart`

### ISSUE THREAD

**Issue by popey456963** [GameServerManagers/LinuxGSM#1600]
I hope I'm not the only one who always types `./csgoserver reload` and then it says it doesn't understand the command.

**Comment by marvinlehmann** [comment]
Reload and restart are just not the same things. It would be kinda misleading. Sorry.

You could also use ` ./csgoserver r`.

**Comment by popey456963** [comment]
@marvinlehmann Oh,  okay!  For future reference, mind if I ask what the difference actually is?

**Comment by marvinlehmann** [comment]
@popey456963 In my experience reload commands are there for reloading settings without actually restarting whatever service. It's like that in e.g. Minecraft or Fail2Ban.

Since LinuxGSM doesn't work that way because it gets newest settings everytime a command is run, it probably would be confusing. I hope it's understandable and correct >.>

**Comment by dgibbs64** [comment]
Postfix also has a reload i think

**Comment by UltimateByte** [comment]
Postfix, Apache as well can reload config files. :)
+1 @marvinlehmann would be misleading incorrect to add a "reload" alias for restart.
