### ISSUE TITLE
server-start.sh issue

### ISSUE THREAD

**Issue by DobriyDed** [GameServerManagers/LinuxGSM#1626]
Cronjob task at nigh found update for application.
During steamcmd app_update process server-start.sh and ..gamenamehere64.json was rewrited.
In result , all memory parameters for java are gone. 
Server start with only 1/4 of needed memory (default params from app) and crashed several times until file changes are found and reversed.

Possible solutions
- create another sh file for server start? (can lead to other issues)
- check base paramers for java and re-write it (too complex?) 
- ????

**Comment by UltimateByte** [comment]
What are you even talking about ? Did I miss an episode or something ?

> Minimum information - to get help
> Which game server you are running (e.g Rust/CS:GO).

https://github.com/GameServerManagers/LinuxGSM/wiki/Support

A link that might help: https://github.com/GameServerManagers/LinuxGSM/wiki/Cronjobs

**Comment by DobriyDed** [comment]
Sorry for my google translate :-)
Project Zomboid server.  appid 380870
Contains start-server.sh and ProjectZomboid64.json by default. 
After issung "pzserver start",  this files used for startup 

During execution of steamcms "app_update" command (pzserver u or fu)  this 2 files was overwrited by update (new version of game comes out yesterday) . Main issue is -Xms and -Xmx parameters  is reset to  default values,far below current server configuration demands.  So , server start to stall from "out of memory". 

Looking for possible problem solutions. As a wild guess, 
* LGSM to create another .sh file for server start ? (can lead to other issues)
* Modify scripts to check base paramers for java and re-write it, if modified by updates (too complex?)

**Comment by DobriyDed** [comment]
As a temporally  solution just revoked write permissions from this files. 
Still looking for better ways

**Comment by Jacksay** [comment]
Hi,
I'm okay with DobriyDed,
Great way will be a paramter added to config server file like `memory=5000`
And LGSM replace in server-start.sh / ProjectZomboidXX.json with that data.

**Comment by MarkL4YG** [comment]
I don't think that would be necessary... using the common and instance configs the setting should persist over updates since only the _default config is overwritten afaik.

**Comment by dgibbs64** [comment]
Is there anything else required for this? If not will automatically close in 30 days

**Comment by markim** [comment]
I just want to put my 2 cents in.

The game updated it's minimum requirements for memory usage. I spawned a server with 1 GB of ram, and was able to follow the LinuxGSM page pretty easily (minus a couple caveats below)

The problem is when all dependencies are there, running

```
./pzserver start
```

The user error is that it just fails to start.

Printing out the console log I can see that it was a minimum memory requirement.
That might be something good print to the screen though!

(About the dependency issue with latest Ubuntu) Also, on a fresh droplet from digital ocean, as root, On Ubuntu 18.10 x64: https://linuxgsm.com/lgsm/pzserver/

I try to run the command to install the packages. First thing I note is I have to preface with:

```
snap install jq
```

Then I can run the majority of the commands on the page (I took out jq):

```
sudo dpkg --add-architecture i386; sudo apt update; sudo apt install mailutils postfix curl wget file bzip2 gzip unzip bsdmainutils python util-linux ca-certificates binutils bc jq tmux lib32gcc1 libstdc++6 libstdc++6:i386 default-jre
```

But then even afterwards I have to run this afterwards to get the snap plug in to get rid of a warning:

```
sudo apt install rng-tools
```

I'm probably not going to check this much more, but thank you all for the hard work and have a great weekend.
