### ISSUE TITLE
Disable Lua-AutoRefresh by default on gmodserver

### ISSUE THREAD

**Issue by MarkL4YG** [GameServerManagers/LinuxGSM#1654]
Reason: Lua files are being refreshed when file changes are detected (Actually saving or just permission changes as any write operation triggers the refresh).

This is not supported or recommended by GarrysMod.

I suggest adding "-disableluarefresh" to the default parameters as the auto refresh should only be used during development processes. This will force users to restart upon changing scripts causing more consistent, reliable and supported behavior and preventing inconsistent bugs.

See: https://wiki.garrysmod.com/page/Auto_Refresh

**Comment by MarkL4YG** [comment]
I've indeed thought about that too.

Hopefully you won't be editing either you other 3rd party scripts on a production environment though. Fixing syntax errors can also be very tricky because as said in the article when refreshing cascades some of the initializations are redone and some aren't which always may break everything in weird manners.  For the same reason reloading in MC servers should only be used in development environments. 

At least to me the deployed lgsm server should not be a development server out of the box. Features soly for development should be disabled.

Just to respond to your concerns.

**Comment by marvinlehmann** [comment]
I just saw that it was actually discussed long ago #590 but I still agree with @MarkL4YG although my knowledge about gmod is quite limited.

**Comment by UltimateByte** [comment]
On #590 the lua autorefresh was just being added to the Linux version of Gmod server, so the point of view was a bit biased. Yeah, this idea of `additional_parms` which later became `customparms`, came from seing multiple request for parms that people might want to change but were a bit questionable to be added by default. 
You're very right to remind it, `customparms` variable would fit perfectly for this case.

@marvinlehmann In that regard, it would be better to add it within customparms="" rather than in main parms="".

**Comment by MarkL4YG** [comment]
@UltimateByte that may well be a compromise between adding it to the default params and not adding it at all.
But honestly wouldn't that compromise the purpose of "custom"-params on the other hand? One big question with this param and LGSM should really be how LGSM wants to deploy servers: In development or production stage.

**Comment by marvinlehmann** [comment]
@UltimateByte Done it. I totally didn't see it >.>

**Comment by UltimateByte** [comment]
This is now merged.
