### ISSUE TITLE
tf2server monitor won't restart server. as it is stuck in an infinite loop. How do I make ./gameserver monitor restart after a few attempts at querying?

### ISSUE THREAD

**Issue by diamondburned** [GameServerManagers/LinuxGSM#1708]
Recently my server started killing itself every morning or so. I checked the console and found this:
>WatchDog! Server took too long to process (probably infinite loop).
>Host_Error: WatchdogHandler called - server exiting.

In `crash.limetech.org`: http://moddageserver.ddns.net/1511474324.png
>engine_srv.so!Sys_Error_Internal(bool, char const*, char*) + 0x1a1
>engine_srv.so!Sys_Error(char const*, ...) + 0x20
>engine_srv.so!Host_Error(char const*, ...) + 0xcc
>engine_srv.so!WatchDogHandler() + 0x12
>linux-gate.so + 0xca0
>vphysics_srv.so!IVP_OV_Tree_Manager::connect_boxes(IVP_OV_Node*, IVP_OV_Node*) + 0x143
>vphysics_srv.so + 0x1248a3
>vphysics_srv.so!IVP_Mindist_Manager::recheck_ov_element(IVP_Real_Object*) + 0x143
>vphysics_srv.so + 0x13b9cf
>vphysics_srv.so!IVP_Environment::simulate_psi(IVP_Time) + 0x135
Note that it says 2 reports share this crash signature. (1 owner / 1 ip) 

My `crontab -e`:
>*/30 * * * * '/home/gyrtf2/tf2server update' > /dev/null 2>&1
>@reboot '/home/gyrtf2/tf2server monitor' > /dev/null 2>&1
>*/1 * * * * '/home/gyrtf2/tf2server monitor' > /dev/null 2>&1

Output of `./tf2server monitor`:
>gyrtf2@notascam:~$ ./tf2server monitor
>[  OK  ] Log-Manager tf2server: Starting
>[ INFO ] Log-Manager tf2server: Removing logs older than 7 days
>[  OK  ] Log-Manager tf2server: Removed 131 log files
>[  OK  ] Monitor tf2server: Checking session: OK
>[ FAIL ] Monitor tf2server: Querying port: 185.215.224.207:27015 : 5/1 : ERROR: Unable to receive^C

^C means Ctrl+C which I pressed because the thing was going on for ever and couldn't restart. I then had to go to Console, do Ctrl+C and start the server again.

My question is: How do I make ./gameserver monitor restart after a few attempts at querying?

**Comment by Nealcaffrey2016** [comment]
Maybe you should add a timeout on the connection,so after a few time try to connect to the game server,the client will quit with a error.




Sent from Neal Caffrey
On 11/24/2017 06:05, diamondburned wrote:

Recently my server starts killing itself every morning or so. I checked the console and found this:

WatchDog! Server took too long to process (probably infinite loop).
Host_Error: WatchdogHandler called - server exiting.

In crash.limetech.org: http://moddageserver.ddns.net/1511474324.png

engine_srv.so!Sys_Error_Internal(bool, char const*, char*) + 0x1a1
engine_srv.so!Sys_Error(char const*, ...) + 0x20
engine_srv.so!Host_Error(char const*, ...) + 0xcc
engine_srv.so!WatchDogHandler() + 0x12
linux-gate.so + 0xca0
vphysics_srv.so!IVP_OV_Tree_Manager::connect_boxes(IVP_OV_Node*, IVP_OV_Node*) + 0x143
vphysics_srv.so + 0x1248a3
vphysics_srv.so!IVP_Mindist_Manager::recheck_ov_element(IVP_Real_Object*) + 0x143
vphysics_srv.so + 0x13b9cf
vphysics_srv.so!IVP_Environment::simulate_psi(IVP_Time) + 0x135
Note that it says 2 reports share this crash signature. (1 owner / 1 ip)

My crontab -e:

*/30 * * * * '/home/gyrtf2/tf2server update' > /dev/null 2>&1
@reboot '/home/gyrtf2/tf2server monitor' > /dev/null 2>&1
*/1 * * * * '/home/gyrtf2/tf2server monitor' > /dev/null 2>&1

Output of ./tf2server monitor:

gyrtf2@notascam:~$ ./tf2server monitor
[ OK ] Log-Manager tf2server: Starting
[ INFO ] Log-Manager tf2server: Removing logs older than 7 days
[ OK ] Log-Manager tf2server: Removed 131 log files
[ OK ] Monitor tf2server: Checking session: OK
[ FAIL ] Monitor tf2server: Querying port: 185.215.224.207:27015 : 5/1 : ERROR: Unable to receive^C

^C means Ctrl+C which I pressed because the thing was going forever and couldn't restart. I then had to go to Console, do Ctrl+C and start the server again.

My question is: How do I make ./gameserver monitor restart after a few attempts at querying?

**Comment by UltimateByte** [comment]
https://github.com/GameServerManagers/LinuxGSM/wiki/Monitor#how-does-monitor-work
