### ISSUE TITLE
Arma 3 Server Centos7 Stuck on Player Connecting

### ISSUE THREAD

**Issue by 4lexftw** [GameServerManagers/LinuxGSM#1724]
I am trying to setup a DS on my VPS too bad no matter what i do the server won't let anyone get to the lobby, the further you can get is at the pre-lobby screen where you can see the background and hear the game ambient sounds, the console only reports: 

**_Player XXXXXX uses modified data
Player XXXXXX connecting_**

But it never connects and nothing happens.

I'll be glad to give you any other piece of information you need to help me figure this out

**Comment by UltimateByte** [comment]
Probably firewall/network issue, follow this first
https://github.com/GameServerManagers/LinuxGSM/wiki/Troubleshooting#connectivity-issues

Since it's most likely not an LGSM issue, it should not be on github, but feel free to re-open this if you find it's a script issue.
https://github.com/GameServerManagers/LinuxGSM/wiki/Support
