### ISSUE TITLE
FastDL errors?

### ISSUE THREAD

**Issue by csgoraw** [GameServerManagers/LinuxGSM#1763]
So i set up fastdl for my server. When i join the server i get errors for all of the models and stuff:

Downloading http://fastdl.****.com/fastdl/materials/models/mudhatk/Mizugoroueye222.vmt.
Error downloading http://fastdl.****.com/fastdl/materials/models/mudhatk/Mizugoroueye222.vmt.

when i go to my fastdl public_html i can see all of the files. The thing is when i go into my materials folder on fastdl all of the models is located in the same folder and not split up into different folders like the server thinks it is?
What can i do? Thank you!

Game: CSGO

**Comment by JimTR** [comment]
I guess you have the sub domain fastdl.***.com set up correctly so fastdl.xxx.com resolves to /home/<user>/public_html/fastdl or wherever you set this domain to point to

**Comment by csgoraw** [comment]
Of cause :)

**Comment by UltimateByte** [comment]
Of course*

CSGO is/was, according to what we know, supposed to have all files mixed, not relative to the original directory. We could change this behavior if you can prove this to be inappropriate.

For testing purposes, you can make a new virtualhost to point to your csgo dir, then block your cfg dir with a .htaccess to make your config safe, and see if downloads occur properly or not. That way, relative paths will be the same as your game dir, since it will be your game dir.

Your issue might as well be due to your files having uppercase characters into it. We all know that Linux game servers usually don't like this since unlike windows, it knows the difference between uppercase and lowercase chars.

**Comment by csgoraw** [comment]
Don't correct me twat.

**Comment by lljsullins** [comment]
Hm, alright. Kinda rude.

**Comment by UltimateByte** [comment]
Ok, do your FastDL by hand then.

**Comment by csgoraw** [comment]
I chose not to use GSM, kid.

**Comment by Alauraa** [comment]
Not to get involved, but your the kid here dude. Grow up and learn to spell better and also to respect others while your at it.

**Comment by csgoraw** [comment]
stfu

**Comment by marvinlehmann** [comment]
@csgoraw Grow up.
