### ISSUE TITLE
Invalid Script URL in install guide

### ISSUE THREAD

**Issue by W0lftastisch** [GameServerManagers/LinuxGSM#1879]
Mhhey! 
I hope this is the right place to post this (haven´t found a website section):

As I was going to install a new instance of terraria, the script URL seems to be broken:

https://linuxgsm.sh instead of https://linuxgsm.com/dl/linuxgsm.sh

![invalidscripturl](https://user-images.githubusercontent.com/36769718/38781716-e0f7b9cc-40e9-11e8-8397-159c48038050.PNG)

This problem occures also in some other games (e.g. 7 days to die)

**Comment by UltimateByte** [comment]
Hi,
Daniel just cleared some website cache and it is now back to normal.

It wasn't supposed to be in the description yet, but it will soon. linuxgsm.sh domain will permit to download the script.
I the meantime if you still want to use it (because it rocks), a solution can be to just replace `https://linuxgsm.sh` with `http://linuxgsm.sh`.
