### ISSUE TITLE
Segfault crashing involving Steam binary (server_srv.so) - Only when server is installed via LinuxGSM

### ISSUE THREAD

**Issue by rdroimfd** [GameServerManagers/LinuxGSM#1884]
I originally made an issue about this over a year ago I think; if I recall it was unable to be replicated and I never figured out what was going on, but thought it was related to LinuxGSM. Recently I've installed a L4D2 server again and have been running into the same exact problem, and am pretty positive it is related to LinuxGSM.

Basically, if you load into an empty server to start a game for the SECOND time, ie. joining, leaving so the server is empty, and joining again (it never crashes the first time), it will crash with a segmentation fault involving server_srv.so in /left4dead2/bin - specifically, the  CSteamWorksGameStatsUploader::GetInterface()" call from server_srv.so.

[Here is the thread I found in the past few days leading me to believe this must be related to LinuxGSM](https://forums.alliedmods.net/showthread.php?t=283920) - This is the only post I've been able to find of someone with the same crashing and debug info. I noticed his errors mention /serverfiles/ directory which if I understand correctly is a folder created by LinuxGSM - meaning his server was run/installed through LinuxGSM as well. I got the same errors running my server through gdb and triggering the crash. The fix mentioned in the thread (installing sourcemod and having it disable the Steamworks stat functionality on the server) solves the crashing. 

So I made two new VM's - One with only [installing the L4D2 server manually following this guide](https://linode.com/docs/game-servers/install-steamcmd-for-a-steam-game-server/), and one doing another vanilla install with LinuxGSM (no mods installed on either server).

I can't trigger any crashing on the server I installed L4D2 via steamcmd manually, and I have the same crashes as before on the new LinuxGSM install.

I remember when I was testing a few days ago, I tried running the server through srcds_run instead of ./l4d2server and still had the same crashing, implying the crashes weren't caused by the l4d2server wrapper (and knowing what I know now, implying whatever is causing the crashes happened during install).

I did the [error fix](https://linode.com/docs/game-servers/install-steamcmd-for-a-steam-game-server/#add-an-error-fix) mentioned here while installing manually via steamcmd - I didn't have the crashes before or after, but it made an error message in the console go away. I'm not sure if LinuxGSM applies the same fix or not when it installs.

So based on all of this, assuming LinuxGSM downloads the exact same files, I'm thinking possibly some kind of permission/symlink/file location problem might be causing this to happen; possibly due to something that changed in mid 2016 (since the person who made [this thread](https://forums.alliedmods.net/showthread.php?t=283920) mentions that it started happening after a certain update).

---Closed this because after 15 minutes of testing the same crashes started happening on the other server.. So this must be a Steam issue

**Comment by UltimateByte** [comment]
Well, your issue could be useful if you gave distro and install info, say for example, the output of postdetails command as per https://github.com/GameServerManagers/LinuxGSM/wiki/Support#required-information-for-support
Without the minimal information about your system, there is no way we can figure out what is going on and solve it.

As per this https://github.com/GameServerManagers/LinuxGSM/wiki/FAQ#i-get-segmentation-fault-how-to-solve-this-issue , segfaults are usually either game server related, or compiler related. In your case, I'd bet on compiler (glibc) since a standalone server works, maybe a glibc fix made by lgsm is causing you more issues than solutions. 

Either way, this is an interesting thing to investigate, but we need your cooperation. Whining about an issue never solved anything, but providing ways to reproduce it works, and it starts at least with distro information, postdetails output link, and any useful details.
