### ISSUE TITLE
/lgsm/config-lgsm/rustserver/rustserver.cfg maxplayers="300" is ignored.

### ISSUE THREAD

**Issue by coldtelling** [GameServerManagers/LinuxGSM#1898]
`maxplayers="300"`
/lgsm/config-lgsm/rustserver/rustserver.cfg

It still says max player 44 ? Any idea why this is ignored ?
servername does work.

**Comment by coldtelling** [comment]
edit: What's actually the max player count, 100 works fine. My bad. But still, I know this isn't your fault but why is there no max-player documentation around ? And how to bypass it like other servers do.

**Comment by UltimateByte** [comment]
We're not a bible. You need to document yourself on the game server you want to run.

**Comment by UltimateByte** [comment]
Rust has a wiki. Who says wiki says you can correct anything wrong and add missing information. I already added a lot of what's in there because their wiki was useless.

Before my contribution: https://developer.valvesoftware.com/w/index.php?title=Rust_Dedicated_Server&oldid=195440
After: https://developer.valvesoftware.com/w/index.php?title=Rust_Dedicated_Server&oldid=206517
Now: https://developer.valvesoftware.com/wiki/Rust_Dedicated_Server

We could add a comment on this line, but since Rust is quite unstable and changes this kind of things every other day, and since there are probably ways to override the value, I'm not sure if this would be relevant anyways. So better update the official Rust documentation.
https://github.com/GameServerManagers/LinuxGSM/blob/master/lgsm/config-default/config-lgsm/rustserver/_default.cfg#L19
