### ISSUE TITLE
[BUG] CWorkThreadPool error after Install server(s)

### ISSUE THREAD

**Issue by BlackYuzia** [GameServerManagers/LinuxGSM#1905]
```
[GAME: Battlation 1944]
[OS: Debian 8]
[User: Kruzya-Pidor]
```
Hi, I get that error after install server (check **GAME**), and I  the same string, when I installed CS:GO server.
That not critical error or that only warning, and not be danger?
```
~/battalion$ CWorkThreadPool::~CWorkThreadPool: work processing queue not empty: 2 items discarded.
```

If you need, I can give more info. 
Thanks for attention.

**Comment by UltimateByte** [comment]
Hi,

Since it does that for multiple game servers, chances are the issue comes from your machine; therefore, it should be resolved on our Steam or Discord. https://linuxgsm.com/support/
We recommend using Debian 9 since Debian 8 is way outdated now.

If you happen to find that this is something that could be fixed within LinuxGSM, please, re-open the issue.

Regards
