### ISSUE TITLE
LSGM Teamspeak Update Option overwrites Teamspeak Beta Installs

### ISSUE THREAD

**Issue by gOOvER** [GameServerManagers/LinuxGSM#1931]
I updated manually Teamspeak to the 3.3.0 beta1. If I have autoupdate enabled, 3.3.0 will be overwritten be 3.2.0. 

Maybe you can add an option to use Beta Build s too order ignore if Version is greater than installed.

"ts3@web01:~$ ./ts3server sp
[  OK  ] Stopping ts3server: TeamSpeak 3 Server
ts3@web01:~$ ./ts3server st
[  OK  ] Update ts3server: Checking for update: teamspeak.com

Update available:
        Current build: 3.3.0 amd64
        Available build: 3.2.0 amd64

Applying update...
extracting teamspeak3-server_linux_amd64-3.2.0.tar.bz2...OK
copying to /home/ts3/serverfiles...OK
"

See also:
https://forum.teamspeak.com/threads/136231-PreRelease-TeamSpeak-3-Server-3-3-0-Beta

**Comment by UltimateByte** [comment]
Managing stable teamspeak versions is already a pain because they don't really have a proper structure to check versions... I think we figured a good way though.
I don't see ourselves working on adding beta repos which would probably change structure quite often and be even more of a pain to maintain. If you want to install the beta version, I would suggest downloading such version to your serverfiles directory manually and update it manually as well.

**Comment by gOOvER** [comment]
Maybe only an option to ignore update when higher than installed.

**Comment by dgibbs64** [comment]
Good idea with the ignoring if the available version is higher. That way you can manually install a beta version and not overwrite it until a newer stable is released.
