### ISSUE TITLE
Add possibility to enter the Steam Guard code through LGSM Install/update

### ISSUE THREAD

**Issue by Rustypredator** [GameServerManagers/LinuxGSM#1988]
Hello, I would like to suggest adding a Feature that enables users to enter their Steam Guard Code when using the Installer/Updater as some servers (like arma3) require a owned copy of the game to download the server.

I find it very annoying to have to use steamCmd manually to update specific servers just because i have to type in my Code.

I think a simple input like its used in the scripts where i can enter the code once it is required would work fine.

**Comment by UltimateByte** [comment]
Hello,

In my opinion, Steam guard does not fit with the purpose of a game server. Update automation and such cannot work with Steam guard which should therefore be disabled for game server. It also causes technical issues where you cannot actually input the password when SteamCMD is started by a script due to the way SteamCMD expects input.

In that regard, I advise making a dedicated Steam account for your game servers in order to minimize the risks on your main account: remember that if your config file is readable by other users they'd have your password. Of course, you shall disable Steam guard on this account for convenience which part of the goal to having a dedicated account for this.

For me it's a "Won't fix" issue.

**Comment by Rustypredator** [comment]
Of course i would rather have a separate Server account, but that would mean buying all games that require you to have said game again for just using an account for servers.  
  
There may be folks out there who can, but i wont pay twice for a game just to use it on a server. thats just ridiculous.  
  
i mean, just make the server public and be done with it.  
  
Also i had a hunch and was right, **The LGSM installer for Arma3 already has that feature**, but the updater doesnt. so i think it would not be as much a task as i initially thought...

**Comment by dgibbs64** [comment]
You don't need to buy the games again. Only q or 2 servers require that

**Comment by dgibbs64** [comment]
The majority of servers are free to access

**Comment by Rustypredator** [comment]
yeah i know, but sadly Arma3 is one of these games :/ and that is one that i use very often, so i have the problem with the guard key pretty regularly. but as the installer already has a system to enter the code, i think it should be easy to implement it into the updater aswell.

**Comment by dgibbs64** [comment]
I'm pretty sure the server is free. As any that are not will say so on LinuxGSM install instructions.

**Comment by dgibbs64** [comment]
No, it doesn't install the game it installs the server package. I should know I wrote the installer.
It uses appid `233780 Arma 3 Server`

https://steamdb.info/app/233780/

I don't see any requirement to make any changes currently.
