### ISSUE TITLE
Fail to install Factorio 0.16.51

### ISSUE THREAD

**Issue by rhodwulf** [GameServerManagers/LinuxGSM#2211]
I want to install the Factorio server, but I get the following error:

`[ FAIL ] Update fctrserver: Checking for update: factorio.com: Not returning version infofctrserver@server-factorio:~$ `

* Distro: [Ubuntu 14.04.5 LTS]
* Game: [Factorio]
* Command: [./fctrserver install]

I think the error may be due to the new version of Factorio 0.17, some parameter moved in the official site that the script fails to read the stable version 0.16.51.

Thank you in advance for your help.

**Comment by RussianRonin** [comment]
So, the grep logic to retrieve the version is incorrect for the latest 0.17.X version. It is looking for 2 characters on the end I think when there is only 1 for now.

**Comment by RussianRonin** [comment]
Also, on the initial install, the version check seems to be checking the experimental version instead of stable because of this line: https://github.com/GameServerManagers/LinuxGSM/blob/master/lgsm/functions/update_factorio.sh#L84

**Comment by rhodwulf** [comment]
That's right, in fact, wanting to make an update to 0.17.2 version , the script "update" to 0.16.51 version, for the comparison you mention, the script "believes" that this is the most recent version, because it only compares the last two digits.

**Comment by rhodwulf** [comment]
How can fix it?.

**Comment by AriosThePhoenix** [comment]
I can confirm that the factorio server install is broken right now. Tried to setup a server on a new VM and I ran into the same error as the user above.

Changing the grep expressions at Line 84/86 so that they match at least 1 character instead of exactly 2 allows the script to grab a version number again, but I didn't have the time to test an actual server install yet

Before: `grep -o '[0-9]\.[0-9]\{2\}\.[0-9]\{2\}'`

After: `grep -o '[0-9]\.[0-9]\{2\}\.[0-9]\{1,\}'`

**Comment by rhodwulf** [comment]
Thanks for reply and fix it, really fast!!! :raised_hands:
