### ISSUE TITLE
[Server Request] Modern Warfare 2 (IW4x)

### ISSUE THREAD

**Issue by MrAmos123** [GameServerManagers/LinuxGSM#2433]
## What game server would you like adding?

Modern Warfare 2 (Specifically IW4x)

## Can you link to any tutorials or guides?

https://iw4x.tumblr.com/post/161974206329/install-iw4x
http://iw4xcachep26muba.onion.to/
https://reactiongaming.us/community/threads/how-to-play-mw2-with-the-iw4x-client-official-installer.920/

## Is the server on Steam?

* [X] No

## Is the server supported on Linux?

We only support Linux servers and do not support Wine.

* [x] Yes

This is a Wine server. May I ask why it doesn't support Wine, it runs perfectly fine? :(

If you cannot make an exception please close this ticket and apologies in advance!

**Comment by Frisasky** [comment]
the aim of lgsm is providing supports for native linux server, we re not an all-in-one project
as theres no native linux support for this server, i would gonna close this server request

**Comment by dgibbs64** [comment]
Hello this in in the FAQ section. https://docs.linuxgsm.com/support/faq#can-you-create-a-server-script-for-a-insert-name-game-server

as @Frisasky only native Linux servers are supported. As this opens a whole "can of worms" for extra support and development requirements that would lead to significant extra work required. For something I believe may not be reliable in all cases as some game servers might work fine with WINE but others will not. So with WINE support there are two options, either fully support it or not at all. Because of this WINE support is considered "out of scope" for the project. I hope this answers your question
