### ISSUE TITLE
Minecraft. "Executable was not found" with "java -cp".

### ISSUE THREAD

**Issue by DezelON** [GameServerManagers/LinuxGSM#2486]
If in the parameter "executable" is "java -Xmx4096M -cp Launcher.jar:Forge.jar net.minecraftforge.fml.relauncher.ServerLaunchWrapper", then an error "CHECK: FATAL: Executable was not found: /home/*****/serverfiles/forge.jar net.minecraftforge.fml.relauncher.ServerLaunchWrapper". It searches for a file, not a class in a file. And this is a bug.

**Comment by Frisasky** [comment]
can you following the bug report template so we can learn the problem better 
thanks

**Comment by h3o66** [comment]
> If in the parameter "executable" is "java -Xmx4096M -cp Launcher.jar:Forge.jar net.minecraftforge.fml.relauncher.ServerLaunchWrapper", then an error "CHECK: FATAL: Executable was not found: /home/*****/serverfiles/forge.jar net.minecraftforge.fml.relauncher.ServerLaunchWrapper". It searches for a file, not a class in a file. And this is a bug.

With the current state this should be placed in the arguments instead of the `executable` parameter.
So for me this does not seem to be a bug at all currently.

For your case you would have needed to add this:
```
fn_parms(){
parms="net.minecraftforge.fml.relauncher.ServerLaunchWrapper"
}
```

if you do not need the existing parameter, feel free to reopen this, if you consider this still a bug.
