### ISSUE TITLE
Rust: error when using mods-update

### ISSUE THREAD

**Issue by sasjafor** [GameServerManagers/LinuxGSM#2498]
## User Story

When I use ./linuxgsm mods-update I get a failure and I believe the relevant part is this error:
`curl: (3) URL using bad/illegal format or missing URL`.

## Basic info

* Distro: Ubuntu 19.04
* Game: Rust
* Command: mods-update

## Further Information

It only started happening today since the new rust update

## To Reproduce

Steps to reproduce the behaviour:
1. Run rust server
2. Run ./linuxgsm mods-update after todays rust update
3. See error `Failure! An issue occurred downloading Oxide for Rust`

## Expected behaviour
No error and working mod update.

**Comment by carek5** [comment]
The same

**Comment by psycomaffo** [comment]
i had the same issue on 3 server, but with a different error on CentOS7...
with the command "mods-update", on 2 server i get
"curl: (3) Illegal characters found in URL
Failure! An issue occurred downloading Oxide for Rust"
and to the otherone i get this
"curl: (3) Illegal characters found in URL
FAIL
https://github.com/theumod/uMod.Rust/releases/download/2.0.4268/Oxide.Rust-LinuxFix.zip
https://github.com/theumod/uMod.Rust/releases/download/2.0.4268/Oxide.Rust.zip"
i already did the update-lgsm but the servers shoutdown immediatly after the start
sry for my bad english and if i'm in wrong to post here

**Comment by carek5** [comment]
https://umod.org/community/rust/12061-server-not-starting-with-oxide?page=8

Helped for me

**Comment by psycomaffo** [comment]
Thanx a lot caker5... i already something like this some hours ago, but i didn't read about the LinuxFix Files.... now all work fine... tnx again

**Comment by lukespragg** [comment]
I believe this is caused by the assumption that the URL used will always have the filename in the URL, which they do not. In this case, our develop URL redirects to a URL that CONTAINS a filename, but doesn't END with a filename as it has arguments in the URL.

The solution would be for LGSM to always set a filename when using curl to grab the file, instead of using whatever the URL may or may not contain as the filename.

https://umod.org/games/rust/download/develop is the URL currently for our Linux builds, which redirects to https://ci.appveyor.com/api/projects/umod/umod-rust/artifacts/Oxide.Rust-linux.zip?pr=false&branch=linux. The redirect is already handled by LGSM, but the filename is not from what I can tell as I believe it tries to get it from the URL.

**Comment by sasjafor** [comment]
I did some testing, and with the PR it does now correctly download and apply oxide. But it does it everytime the mods-update command is run. So it doesn't seem to detect that oxide is already up to date.

**Comment by Frisasky** [comment]
lgsm did not detect which version installed, it just fetch latest version and overwritten old files

**Comment by sasjafor** [comment]
Yes. But I thought it did detect it before? Because I run it with a cronjob. So I don't want it downloading oxide everytime that command runs.

**Comment by Frisasky** [comment]
all mod related function are included in this file, you did not find a function called check mod version, right?
https://github.com/GameServerManagers/LinuxGSM/blob/master/lgsm/functions/mods_core.sh

**Comment by sasjafor** [comment]
Alright, I'll open a feature request then.
