### ISSUE TITLE
QuakeWorld Server Support

### ISSUE THREAD

**Issue by Xylemon** [GameServerManagers/LinuxGSM#250]
This one would be a bit tricky considering there are so many Quake Engines, but this would be really great to have.

**Comment by Xylemon** [comment]
I think it would be better having a QuakeWorld server rather than just a Quake server. I'd also recommend using this for the server binary: https://github.com/deurk/mvdsv

**Comment by dgibbs64** [comment]
I have taken a look at the number of Quake World servers and there are only a few. I dont think at this time there is enough demand for this server considuring the amount of time is would take to create. If it was a pre existing engine that woudl be different. Because of this I will close. Anyone who would like this server is welcome to create it and submit a pull request
