### ISSUE TITLE
[Starbound] Add GSLT support

### ISSUE THREAD

**Issue by jeremiergz** [GameServerManagers/LinuxGSM#2591]
Hi guys!

First of all, big fan of the project, thanks for the good work!

I'd like to know if Steam GSLT support can't be added to Starbound. As of now, you have to enter your steam username/password & it's not the best secure way. I don't know if there are limitations preventing implementation of those tokens.

Thanks!

**Comment by dgibbs64** [comment]
GSLT is not related to the download of the serverfiles

the login details are related to SteamCMD. https://docs.linuxgsm.com/steamcmd#steam-user-login
GSLT is related to game server persistence. https://docs.linuxgsm.com/steamcmd/gslt

If Starbound does support GSLT then it can be added. But im not sure it actually does.

**Comment by jeremiergz** [comment]
I may be mistaken but it appears that these tokens can be used to log your server in instead of using your username/password creds.

https://steamcommunity.com/dev/managegameservers

**Comment by dgibbs64** [comment]
GSLT can not be used as a substitute to login to a steam account, as this, not the purpose GSLT. Steam login and GSLT are completely unrelated.

Starbound server is built into Starbound game client, because of this you need to login to a Steam account that owns a copy of Starbound.

So I think you have misunderstood the purpose of GSLT.

**Comment by jeremiergz** [comment]
I totally misunderstood yeah, thanks for clearing that out!
