### ISSUE TITLE
Unable to have separate (ark) servers in one user home directory

### ISSUE THREAD

**Issue by pleinx** [GameServerManagers/LinuxGSM#2692]
Hey Guys,

i setup today fresh install of my Gameservers. I want to have one user called "arkservers" with multiple sub-directories for each **own** ark-server.

The Reason is, its much easier to handle the clusters and file permission issue with ark-server.

## The Setup
```
$ /home/arkservers/ark1
$ /home/arkservers/ark2

$ /home/arkservers/ark1: wget -O linuxgsm.sh https://linuxgsm.sh && chmod +x linuxgsm.sh && bash linuxgsm.sh

$ /home/arkservers/ark2: wget -O linuxgsm.sh https://linuxgsm.sh && chmod +x linuxgsm.sh && bash linuxgsm.sh

$ /home/arkservers/ark1: ./linuxgsm.sh install
$ /home/arkservers/ark2: ./linuxgsm.sh install
```

This works. I made my different server-settings betweens these installations (ofc also with other query-port, rcon etc).

Now the issues:

I'm starting server#1
```
$ /home/arkservers/ark1: ./arkserver start
```

I'm trying to start server #2:
```
$ /home/arkservers/ark2: ./arkserver start
```
But got the error that the server is already running. I checked the system resources but only the server#1 is running.

What i'm doing wrong?

## Basic info
* **Distro:** [Ubuntu 18.04]
* **Game:** [Ark Survival Evoled]
* **LinuxGSM version:** latest

**Comment by Grimston** [comment]
The problem you have is they are sharing the same process name (arkserver) so it will detect the first server and not start the second.

Instead of doing it this way you can combine the following information on clusters with a multi-user setup.

**Initial cluster setup**
```shell
mkdir /srv/ark/clusters
chown nobody:nogroup -R /srv/ark/clusters
chmod -R 2777 /srv/ark/clusters
```

**Set up links to the shared folder**
```shell
# Link Server 1 to the shared folder, this should be done AS the user for Server 1
ln -s /home/ark1/serverfiles/ShooterGame/Saved/clusters /srv/ark/clusters

# Link Server 2 to the shared folder, this should be done AS the user for Server 2
ln -s /home/ark2/serverfiles/ShooterGame/Saved/clusters /srv/ark/clusters
```

**Comment by pleinx** [comment]
Thanks @Grimston this temp. solution comes from me (discord) first time it seems to work but only because my service (which triggers every 2secs the script) override the file permissions.

And i know thats not nice, thats why i'm trying to put all my ark-servers into one user directory, but wont work...

**Comment by bogdandorca** [comment]
As @Grimston mentioned, when you start servers using `./arkserver` start, all the processes started will share the same name.

The work-a-round I'm using is renaming each server file. This will start every server with an unique process name.

My set-up is as follows:
The `ark` folder has all my servers: `server-1`, `server-2`, `server-3`...
When I installed the game in `server-1` I renamed the `arkserver` file to `ark-server-1`.
On the second server, I renamed it to `ark-server-2`.

If you're using this approach, please make sure you freshly install the game after renaming the file as some configuration files will have to be generated accordingly (for example, the `arkserver.cfg` will now be named `ark-server-1.cfg`).

Now, in order to start the first server, user `./ark-server-1 start`.

> wget -O linuxgsm.sh https://linuxgsm.sh && chmod +x linuxgsm.sh && bash linuxgsm.sh arkserver
> 
> mv "./arkserver" "./ark-server-1"
>
> ./ark-server-1 install
>
> ./ark-server-1 start

**Comment by pleinx** [comment]
@bogdandorca thanks for your support, for now it works perfectly, will give you finally feedback the weekend if i have all servers setup like this :)

**Comment by pleinx** [comment]
it works perfectly, tested with 3 servers in a cluster, good job

**Comment by sapphirecz** [comment]
According to the this page in [Cross-ARK Data Transfer](https://ark.gamepedia.com/Server_Configuration#GameUserSettings.ini) you dont have to setup links from your cluster folders. You can set up one cluster folder for all your gameservers under one user:

247.85 added the ability to specify a common cross-server storage location that functions between multiple servers running on the same machine by adding the following launch parameter to each server:
`-ClusterDirOverride=C:/TestStorage/`

Example:
`fn_parms(){
parms="\"${defaultmap}?AltSaveDirectoryName=${defaultmap}?listen?MultiHome=${ip}?MaxPlayers=${maxplayers}?QueryPort=${queryport}?RCONPort=${rconport}?Port=${port} -automanagedmods -NoTransferFromFiltering -clusterid=YOURID -ClusterDirOverride=/YOURCLUSTERFOLDERPWD/\""
}
`
