### ISSUE TITLE
Unable to start Ark server after last update (START: FATAL: command_start.sh exiting with code: 1 )

### ISSUE THREAD

**Issue by Mixtery** [GameServerManagers/LinuxGSM#2693]
Ark server refuses to start. Says FAIL: Unable to start Ark Server. 
In the logs i find START: FATAL: command_start.sh exiting with code: 1 . 

Please assist...

**Comment by Grimston** [comment]
This is a problem on Arks end please see this [forum thread](https://survivetheark.com/index.php?/forums/topic/507564-genesis-dedicated-server-error/) regarding it:

**Comment by Tobstr02** [comment]
I also have an error since the last update.
`[ INFO ] Starting arkserver: Check IP: *****
[ .... ] Starting arkserver: LinuxGSMno server running on /tmp/tmux-1000/default
[ FAIL ] Starting arkserver: Unable to start LinuxGSM`

If i try ./arkserver debug it says
`./ShooterGameServer: error while loading shared libraries: libsteam_api.so: cannot open shared object file: No such file or directory`

I didn't changed anything... i also tried to reinstall the whole server.
Because I was desperate, I also reinstalled the complete virtual server, but i didn't helped.

**Comment by Mixtery** [comment]
Read the page Grimston posted. The solution is there.
