### ISSUE TITLE
Getting Steam API Connect Error #RustServer

### ISSUE THREAD

**Issue by harpreet9629** [GameServerManagers/LinuxGSM#2787]
## Basic info

* **Distro:** Centos 7
* **Game:** Rust
* **Command:** [Monitor]
* **LinuxGSM version:** [v12.34.56]

## Expected behaviour

I am getting error 

Redirecting stderr to '/home/rustserver/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...Failed to init SDL priority manager: SDL not found
Failed to set thread priority: per-thread setup failed
Failed to set thread priority: per-thread setup failed

**Comment by Frisasky** [comment]
you can just ignore this error message

**Comment by dgibbs64** [comment]
Recent SteamCMD error. This is a non-issue and causes no problems with running SteamCMD.

**Comment by dgibbs64** [comment]
This requires some new documentation

**Comment by Mundo-Minecraft** [comment]
I have the same error when installing 7 days to die on ubuntu server 18.04. But I see that you comment you can use steamcmd perfectly. But when this error comes out, the installation does not continue and does not download the 7 days to die. How do you skip this error so that the installation continues?
Thanks.

**Comment by Mundo-Minecraft** [comment]
> Recent SteamCMD error. This is a non-issue and causes no problems with running SteamCMD.

I have the same error when installing 7 days to die on ubuntu server 18.04. But I see that you comment you can use steamcmd perfectly. But when this error comes out, the installation does not continue and does not download the 7 days to die. How do you skip this error so that the installation continues?
thanks.

**Comment by h3o66** [comment]
@Mundo-Minecraft try to validate the gamefiles `./sdtdserver validate`

**Comment by dgibbs64** [comment]
documentation added and refactor to better handle steamcmd errors #2959
