### ISSUE TITLE
use xz compression instead of bzip2 for non-steam

### ISSUE THREAD

**Issue by dgibbs64** [GameServerManagers/LinuxGSM#2816]
## User Story

As a developer, I want migrate to using xz compression to speed up installation (decompression time) and save space on the hosting server.

## Basic info

* **Command:** install

## Further Information

Did a small amount of research and found that xz offered better compression reducing file size and decompressing much faster at around double the speed when I tested this.

```
ut2004-server-3369-2-ultimate-linux.tar.xz | size: 1.56GB decompress: 60MB/s
ut2004-server-3369-2-ultimate-linux.tar.gzip | size: 2.03GB | decompress: 60MB/s
ut2004-server-3369-2-ultimate-linux.tar.bz2 | size: 1.9GB | decompress: 25MB/s
```
Looking at compatibility xz is supported as far back as 16.04 centos 7 and debian 8 so this will not be a problem with compatability.

## Further Reading

Provide any useful documentation or resources that might help.

**Comment by UltimateByte** [comment]
If we can trust this: https://unix.stackexchange.com/questions/301587/why-should-i-use-tar-xz-instead-of-tar-gz-xz-is-a-lossless-data-compression-pro/301590
gzip is easier to support since it's more universally installed everywhere. But xy has better compression ratio for similar extracting time, while taking more time to compress.

**Comment by dgibbs64** [comment]
I did the testing myself and xz was the best and its available on all supported distros so happy to use it

**Comment by h3o66** [comment]
~Closed
refactor in version 20.3.0 included
