### ISSUE TITLE
Near Instant Auto Restart of Failed Server Process

### ISSUE THREAD

**Issue by Annihilator** [GameServerManagers/LinuxGSM#3014]
LinuxGSM autorestarts failed servers when the periodic monitor detects that they're down. Fine and dandy, but potentially too slow. Many players who attend a failed server will not remain unless it restarts quickly. Also, for some games and in some particular situations, if the server restarts quickly enough, the players may not even notice that it went down at all.

The LinuxGSM wrapper script which starts the dedicated server process should be able to instantly detect when that process fails, and proceed to restart it immediately. In order to prevent the situation when the script attempts to restart a completely failed server ad infinitum, a counter should be in place which stops more than X "instant restart" attempts. The monitor portion of LinuxGSM takes it from there, for future restart attempts.

**Comment by dgibbs64** [comment]
the only way this would be possible is to be constantly checking the process is running. While this might detect some crashes it wont detect others as servers can crash while the process still running. In this instance query is useful. However, some servers stop responding to query while map changes are happening, which is why monitor will delay for 1 minute before restarting.

It would also make sense to address why the server is crashing rather than relying on linuxgsm to regularly restart it.

cron has the minimum of running every 1 minute to get anything less would require linuxgsm be running a constant loop checking every few seconds. In the case of a process crash the current fastest possible is up to 1 minute for querys its up to 2 minutes for a restart.

So I can see some specific cases of process monitoring being a big faster but others would not
