### ISSUE TITLE
Soldier of Fortune 2: Double Helix server issue

### ISSUE THREAD

**Issue by jobhh** [GameServerManagers/LinuxGSM#3145]
## User Story

_This issue was created per instruction from @dgibbs64 responding to a post from last month: https://github.com/GameServerManagers/LinuxGSM/issues/2210#issuecomment-723167876. 
@tkrn indicated this issue can be assigned to him_

As a friend of a Soldier of Fortune 2: Double Helix fan, I figured I'd make him happy and play the game with him in these COVID-19 days. I noticed that I couldn't join a clean LinuxGSM sof2 server with a clean GOG sof2 installation. I got the error shown in the image below while the default server setting is "seta sv_allowDownload "1"".

![sof2_server_issue](https://user-images.githubusercontent.com/2331451/98388738-6db6c100-2053-11eb-83cd-b16a2901bcac.jpeg)

## Basic info

* **Distro:** [Debian 10 Buster 64bit]
* **Game:** [Soldier of Fortune 2: Double Helix]
* **LinuxGSM version:** [v20.5.1]

## Further Information

While trying to troubleshoot I also noticed there is no 1fx folder after the server installation. I read in [the Server Request issue for Soldier of Fortune 2](https://github.com/GameServerManagers/LinuxGSM/issues/2210) that the server creator mentioned the server side "1fx. Mod", was this included in the LinuxGSM installation?

## To Reproduce

Steps to reproduce the behaviour:
1. Install LinuxGSM and sof2server [per instructions](https://linuxgsm.com/lgsm/sof2server/)
2. Buy and install [GOG SOF2 version](https://www.gog.com/game/soldier_of_fortune_ii_double_helix_gold_edition)
3. Launch SOF2 and attempt to enter server
4. See message

_Edit: 
I think the type:bug label can be removed... It's not a bug in LinuxGSM itself._

**Comment by tkrn** [comment]
I cannot replicate the problem. Fresh install of sof2server with the default master branch. Also, fresh install of SOF2GOLD 1.03. Can you confirm your version by going into SOF2, ` over to console and issue a "\version". Please take a screenshot and attach it to this bug.

![2021-01-14_21-09-11](https://user-images.githubusercontent.com/4492419/104672063-077e9800-56ad-11eb-98bb-695f1f16604c.png)

![2021-01-14_21-08-23](https://user-images.githubusercontent.com/4492419/104672065-08172e80-56ad-11eb-98ac-ed844a5b187f.png)

**Comment by tkrn** [comment]
@jobhh awaiting input

**Comment by jobhh** [comment]
My apologies for the delay.

I removed SOF2 and did a clean install from the GOG Galaxy client. This is the client info:
![image](https://user-images.githubusercontent.com/2331451/107118289-4ce34f00-6880-11eb-96bf-292aa904c616.png)

I also cleared my SOF2 LinuxGSM installation and did a clean install: [install log.txt](https://github.com/GameServerManagers/LinuxGSM/files/5936832/install.log.txt)
This are the LinuxGSM server details: [server details.txt](https://github.com/GameServerManagers/LinuxGSM/files/5936829/server.details.txt)
I checked the console output when I tried to connect: [console output.txt](https://github.com/GameServerManagers/LinuxGSM/files/5936828/console.output.txt)
Sadly, I was disconnected. It still fails on trying to download update103.pk3.

I did figure out what the issue is though.
**It turns out the GOG installation and the LinuxGSM installation have different update103.pk3 files.** The update102.pk and update101.pk do have the same file content.

LinuxGSM checksums:

    5151704382CABA677F4642E2B0A88A2ED19CE929C1D75EACEC8BDDF89106E2CE  SHA256  update103.pk3
    2C9F60D9FE1402E32EE6CBBA8938B95A59F2B7E05D56A4AE87433DB96A77BC9B  SHA256  update102.pk3
    FE407539B13866C831F1009E19C919AB717D5E428F4F973DE2D111FACBD672A7  SHA256  update101.pk3

GOG checksums:

    2797E7F1A50E7C7CE29C67C624BF02066EF0F679072E8B6897C67A584F99D0C2  SHA256  update103.pk3 (no match)
    2C9F60D9FE1402E32EE6CBBA8938B95A59F2B7E05D56A4AE87433DB96A77BC9B  SHA256  update102.pk3 (match)
    FE407539B13866C831F1009E19C919AB717D5E428F4F973DE2D111FACBD672A7  SHA256  update101.PK3 (match) (sidenote: PK3 is in capitals here)

Is the LinuxGSM or GOG version the original update103.pk3 file? Is there something we can do about this? 
Simply replacing my update103.pk3 with the version of LinuxGSM shows me this error message when attempting to join the server: `Client/Server game mismatch: sof2mp-1.02/sof2mp-1.03`. Even though the console "\version" command shows V1.03 in my client.

Unrelated question: I read in the Server Request issue for Soldier of Fortune 2 that you mentioned the server side "1fx. Mod", was this included in the LinuxGSM installation, I didn't see a 1fxmod directory?

**Comment by tkrn** [comment]
This is interesting and great detail. Thank you. After review, the server bundle came from the orignal sof2goldfull.exe (SHA256 F8C05D0F805D83CCA1512333BC558ADCC57DE97F1F953FF023E724C819F2EA95) patch released 11/27/2002 - https://www.gamefront.com/games/soldier-of-fortune-2/file/soldier-of-fortune-2-double-helix-gold-full-patch 

These are the file hashs from a fresh patch from sof2goldfull.exe:
FE407539B13866C831F1009E19C919AB717D5E428F4F973DE2D111FACBD672A7  SHA256  update101.PK3 (match)
2C9F60D9FE1402E32EE6CBBA8938B95A59F2B7E05D56A4AE87433DB96A77BC9B  SHA256  update102.pk3 (match)
5151704382CABA677F4642E2B0A88A2ED19CE929C1D75EACEC8BDDF89106E2CE  SHA256 update103.pk3 (no match)

It appears there is a difference in update103.pk3 in the Offical patch vs what is included in the GOG edition. Can you do me a favor to test since I don't have the GOG edition, rename your update103.pk3 to update103.bak and try the one from the official patch? I uploaded it here for you to grab quickly to test with, [](http://tkrn.io/u/tkrn/update103.pk3) You have the hashes to match it to the download if needed.

**Comment by jobhh** [comment]
I already tried replacing the GOG update103.pk3 with the official version ;) It sadly din't allow me to join the server.

> Simply replacing my update103.pk3 with the version of LinuxGSM shows me this error message when attempting to join the server: Client/Server game mismatch: sof2mp-1.02/sof2mp-1.03. Even though the console "\version" command shows V1.03 in my client.

I could get you the GOG version if it would help to evaluate the issue further?

**Comment by tkrn** [comment]
After a bit of digging, GOG modified the original pk3 you can see this in the attached image with the 2018 date code. The sv_pure is already set to 0 which should allow this to connect. I've also noticed in the GOG edition, there is no multiplayer menu and how do you access the console? I'm unable to with `

![sof2-gog-update103-pk3-modified](https://user-images.githubusercontent.com/4492419/107419688-1149be80-6ae6-11eb-9a73-e05dbbd1bb8a.png)

**Comment by tkrn** [comment]
I made some traction. The latest binary that Raven ever released for the dedicated server was only ever 1.02a. When you browse the server information on a server, you'll see the server version being that. When you play with the original Raven patch of 1.03 SOF2 Gold connecting to the 1.02a dedicated Linux server was never an issue. 

The GOG version made some modifications to the game for whatever reason (technical/legal/etc). What I see that there are three dlls that never existed in the original game these are located under the base/mp folder. The base/mp folder only ever held the cdkey, a config file (maybe) and the PunkBuster Client GUID which was a deliberative off the cdkey. With all that said, GOG introduces these sof2mp_* dll which are modified versions of the original. The originals (cgamex86.dll, gamex86.dll and menusx86.dll) can be found in the root directory. 

After some trial and error, it appears these do not need to be present for the multiplayer to work. These files are much smaller than the original renamed equals. I renamed the dlls that were in base/mp to .bak so that the hooks wouldn't load those libraries. After that, the game functioned and connected to the server successfully.

I don't perceive these are necessary for it to function. If they are needed after more testing of this, then I would say let's grab the original libraries from the official Raven 1.03 patch and name them accordingly (sof2mp_cgamex86.dll, sof2mp_gamex86.dll and sof2mp_uix86.dll)

**Solution for GOG SOF2** Rename/delete the dll files from base/mp folder.

![sof2_dll_rename](https://user-images.githubusercontent.com/4492419/107539968-86270200-6b93-11eb-91d5-19193e993840.png)

**Comment by jobhh** [comment]
Thank you for investigating this!
I've tested the solution you mentioned and it seems, in addition to removing those dll files, we still require the Raven version of the update103.pk3 file before the GOG version of the game can join a LinuxGSM server.

1. Clean GOG install and renamed the sof2mp_***.dll files from the base\mp folder, with update103.pk3 untouched.
Result: `Could not download "base/update103.pk3" because autodownloading is disabled on the server. etc...`

2. Clean GOG install and replaced update103.pk3 with the LinuxGSM version, with the dll files untouched. 
Result: `Client/Server game mismatch: sof2mp-1.02/sof2mp-1.03`

3. Clean GOG install, renamed the dll files and replaced update103.pk3 with Raven version.
Result: `Succesfully joined the server.`

So, we have a working solution :) I don't think there is much we can do about this from a LinuxGSM perspective, right? Apart from maybe contacting GOG and asking why they made this change.

One final question: I noticed there is no 1fx folder after the server installation. I read in the [Server Request issue for Soldier of Fortune 2](https://github.com/GameServerManagers/LinuxGSM/issues/2210) that you mentioned the server side "1fx. Mod". Was this included in the LinuxGSM installation?

**Comment by dgibbs64** [comment]
Interesting stuff. I think the next step is to contact GoG and get some info from them about why there are changes. I recommend pointing them in the direction of this issue for all the details.

**Comment by jobhh** [comment]
Small update:
I've contacted GOG and received a pk3 and pk4 file to test with. The pk3 is the original pk3, and the pk4 does not seem to interfere with joining the server.

This seems to fix this error: 
`Could not download "base/update103.pk3" because autodownloading is disabled on the server. etc...`

I've replied that the pk3/pk4 files seem to work and asked them if there is also something they can do about the 3 dll files, to fix this error: 
`Client/Server game mismatch: sof2mp-1.02/sof2mp-1.03`

To be continued.

**Comment by dgibbs64** [comment]
A brilliant update. Thanks for that @jobhh I look forward to further updates

**Comment by jobhh** [comment]
It seems like GOG fixed the issues :)
 I noticed an update in GOG Galaxy, so I did a clean install and I can now join a LinuxGSM server without altering any files.
The update103.pk3 file is the original one, GOG added update104.pk3, and the dll files are no longer included.

![image](https://user-images.githubusercontent.com/2331451/113779942-bc65a580-972e-11eb-89c6-47756990f2e7.png)

Which means we can close this issue :) Thank you for the support @tkrn!
If you would indulge me one last time, could you answer this question? I read in the [Server Request issue for Soldier of Fortune 2](https://github.com/GameServerManagers/LinuxGSM/issues/2210) that you mentioned the server side "1fx. Mod". Was this included in the LinuxGSM installation?

**Comment by dgibbs64** [comment]
That's brilliant news!

**Comment by tkrn** [comment]
Great news and thanks for reaching out to GOG it's great to hear they were responsive to the request. That's promising for future game servers under their distribution.

1fx mod was included in my first package of this but I goofed. It should have been a mod add on not apart of the base package. 

It's my intention to add 1fx back on but as a mod using the LGSM mod add/remove feature. I'm currently a new father so it'll be coming but can't promise when. @jobhh thanks again for all your help and support!

**Comment by tkrn** [comment]
@jobhh For record sake can you drop the hashes of the latest files so we know what files are known good? After that I'll close up this issue ticket. Thanks!

**Comment by jobhh** [comment]
Congratulations on becoming a father! Go and spend plenty of time with your family, enjoy :)

These are the functional GOG checksums:

    FE407539B13866C831F1009E19C919AB717D5E428F4F973DE2D111FACBD672A7  SHA256  update101.PK3 (match with LinuxGSM)
    2C9F60D9FE1402E32EE6CBBA8938B95A59F2B7E05D56A4AE87433DB96A77BC9B  SHA256  update102.pk3 (match with LinuxGSM)
    5151704382CABA677F4642E2B0A88A2ED19CE929C1D75EACEC8BDDF89106E2CE  SHA256  update103.pk3 (match with LinuxGSM)
    934C2AF7DF966339B9DD0FF705934A0F8E01E21B8645A9C559AC2F0B3024AFFE  SHA256  update104.pk3 (new file)

Perhaps also interesting, this is the update104.pk3 content:
![image](https://user-images.githubusercontent.com/2331451/113826013-f57b3580-9781-11eb-87fc-ccae65cda01a.png)
