### ISSUE TITLE
[BUG] Updating csgoserver: SteamCMD: Unknown error occured

### ISSUE THREAD

**Issue by EvanChrisp** [GameServerManagers/LinuxGSM#3271]
## User Story

As a user, I want a better error message so that i am able to debug easier.

## Basic info

* **Distro:** Debian 10
* **Game:** CSGO
* **Command:** update
* **LinuxGSM version:** v21.1.3

## Further Information

I have 2 CSGO servers and the maps folder is symlinked so that I can save time and storage. But when I updated the 2nd server i received the error 
`Connecting anonymously to Steam Public...Logged in OK
Waiting for user info...OK
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
Error! App '740' state is 0x606 after update job.
Error! Updating csgoserver: SteamCMD: Unknown error occured
Failure! Updating csgoserver: SteamCMD: Did not complete the download, too many retrys
`

It took me a while to debug, but i finally realised it was because the 2nd server user didnt have write permissions to the linked maps folder. I imagine this error would happen with most games if the game files are symlinked. 

## To Reproduce

Steps to reproduce the behaviour:
1. Symlink game files
2. Attempt to update the 2nd server
3. See error

## Expected behaviour
This can be fixed by giving write permissions to the 2nd user. But an error message explaining the permissions issue would help people with this issue in the future.

**Comment by rconjoe** [comment]
This isn't a bug in LinuxGSM. As symlinked files to not have independent permissions and inherit the permissions of the files they point to, this behavior is expected.

**Comment by dgibbs64** [comment]
This will be an interesting one for the docs. I am compiling a list of errors for steamcmd

https://docs.linuxgsm.com/steamcmd/errors#error-0x606

We have no info on the error itself. If still available @EvanChrisp please can you provide the steamcmd content.log

https://docs.linuxgsm.com/steamcmd/errors#steamcmd-logs

It would suggest that a permissions issue caused the problem. This is normally picked up by LinuxGSM but since there is an edge case of using a symlink it probably missed it. 

Re-opening to to gather more info on the error message. Once confirmed LinuxGSM we can update the docs and will be able to output a usage error message here https://github.com/GameServerManagers/LinuxGSM/blob/master/lgsm/functions/core_dl.sh#L89

**Comment by EvanChrisp** [comment]
Hopefully this helps.

[content_log.txt](https://github.com/GameServerManagers/LinuxGSM/files/6001324/content_log.txt)

**Comment by dgibbs64** [comment]
@EvanChrisp thats brilliant thanks. 

```
[2021-02-18 02:23:13] AppID 740 state changed : Update Required,Fully Installed,Update Queued,Update Started, (Disk write failure)
```

Pretty much confirms the permissions issue.

I'm assuming this is the symlink?
```
/home/csgoserver3/serverfiles/csgo/maps/cfg
```

**Comment by EvanChrisp** [comment]
> I'm assuming this is the symlink?
> 
> ```
> /home/csgoserver3/serverfiles/csgo/maps/cfg
> ```
The symlink is just /home/csgoserver3/serverfiles/csgo/maps/, but it appears the file
`/maps/cfg/guardian_op10_mirage_b.cfg` got updated in todays CSGO update, so i assume that was the reason it was attempting to write to the /cfg/ folder
