### ISSUE TITLE
[Server Request] Minecraft

### ISSUE THREAD

**Issue by Zer0t3ch** [GameServerManagers/LinuxGSM#333]
Are there plans to add a minecraft server? If not already in motion, I might try to implement it myself and just submit a pull request.

**Comment by Scarsz** [comment]
It's hard to considering the pain it is to get the latest spigot version.

**Comment by Zer0t3ch** [comment]
Why Spigot, specifically? We could do just a vanilla server, fetching from minecraft.net shouldn't be hard, and configuration is a breeze.

**Comment by Zer0t3ch** [comment]
Though Spigot would also be cool to have.

**Comment by Scarsz** [comment]
Truth is, nobody nor their mother uses the default MC server for running a public MC server, no plugins and minimal management options.

I'll see if I can get something for Minecraft for LGSM sometime tonight or tomorrow, either or.

**Comment by Zer0t3ch** [comment]
Oh, I totally understand this. Frankly, I was using this tool to quick-deploy stuff for me and my friends to play on. Thought vanilla minecraft might be a good fit, and considering the simplicity, there's really no good reason not you add it. Though, adding a spigot server would be cool. My understanding of how the newer versions work (which is minimal) makes it seem as if adding it would actually be pretty easy.

**Comment by Scarsz** [comment]
The script will have an option to install the vanilla Minecraft server from Mojang or to compile & build the latest Spigot release, might add an option for Cauldron, undetermined

**Comment by dgibbs64** [comment]
You are welcome to create a minecraft server script if you like. I don't know enough about minecraft to implement one myself. :)

**Comment by Roversword** [comment]
personally I do not think that is easily possible unless you aim for the absolute vanilla server with no mods.
The very fact it needs a tremendous amount of tweaking once you have more than two or three mods (usually the known modpacks have about 100) is impossible to handle with a script...and the updates...even worse.
So, having a "simple" script like for insurgency or cs:go for minecraft (other than maybe vanilla) is very improbable. But that is just IMHO.

**Comment by Zer0t3ch** [comment]
@Roversword Well with spigot, they have switched to a system as simple as executing a `.jar` file to download and compile the Spigot source. Should be easy for an installer/updater script. I think there's a system on mojang's server to detect what version is the newest and to download any version you want, so should be just as easy-ish as any other server, it's just not as easy as things like SteamCMD make it.

**Comment by Zer0t3ch** [comment]
@Scarsz Are you actively working on adding the script right now? If not, I'll probably take a shot at it, though I have a very *very* ***very*** limited understanding of the existing codebase.

**Comment by originalwhitestar** [comment]
I'd like to see a minecraft server too :p

**Comment by GeenoMC** [comment]
@Scarsz wow

**Comment by UltimateByte** [comment]
I already made a standalone server once.
Wasn't that hard !
Somebody just talked to me about MC. 
Thought it'd be a good idea to add support for it ! I'm adding this to my checklist, i'll figure out how to make this possible !

**Comment by Zer0t3ch** [comment]
@UltimateByte Yeah, initial setup is super easy. I'm just not sure how/if updates and whatnot should be handled. In the case of vanilla, the worst thing that comes out of a server update is that the clients can't play until they update as well. 

In the case of modded, you have to deal with all kinds of potential things breaking.

**Comment by UltimateByte** [comment]
Well, that can be a huge deal... Do some mods actually replace game files ?
Can you update this game just by replacing older files ? Or do you have to cleanup the whole thing every time ?

**Comment by JimTR** [comment]
why not leave it to https://github.com/sandain/MinecraftServerControlScript

**Comment by UltimateByte** [comment]
I didn't know about that script.
The good thing about LGSM is that it's a centralized and unified script.
I'm gonna try contact him to see if we could port his script.
Otherwise i'll go from scratch.

**Comment by UltimateByte** [comment]
OK, the discussion evolved quite well, i think i'll be able to make a mix between his script and a whole new one integrated to LGSM.

Note to myself : Watchout the update process
Manage autobackup to autoremove some, otherwise a small space server can get full quite fast (experienced this issue when i had an MC server).

**Comment by sandain** [comment]
I didn't write the code in mscs that handles backups, but we have been using rdiff-backup for quite a while to help avoid filling a small server space.  Unless LGSM has some built-in mechanism for backups already, I would suggest just using the mscs code.

**Comment by UltimateByte** [comment]
LGSM has some functions to manage older scripts already, i can get some inspiration from that and use google to find more ideas.
I won't hide such functions are quite new to me, but it's doable. I feel ready now i gave birth to my new baby, the zip updater. :o)) This is relevant to mention that, because i want to make a function to keep a specified amount of backups in it, so it will have to remove older ones... And once i know how to do that, i'll be able to remove older backups from mcserver. ^^
I prefer not using external programs though, unless they are in bash open source already, so we can use some of their code and integrate it to LGSM. ^^

**Comment by Zer0t3ch** [comment]
@UltimateByte The issue with mods and updating isn't so much that the mods modify any server files, (although some things like Bukkit require you to actually run special server JARs, not just the vanilla one) the problem is that if you have MC 1.7 with a bunch of mods and you update to 1.8, none of those mods will work.

**Comment by UltimateByte** [comment]
@Zer0t3ch Thanks for the info. Well, it's the same as Rust, Hurtworld, and some updates of source games that breaks addons... Maybe a warning about that should be printed when updating, i don't know what else we could do. I made a script to update zip addons though, it could help. ^^

**Comment by Zer0t3ch** [comment]
@UltimateByte What I would suggest is something like this:

Upon installation, it would prompt for server type and manage accordingly:

- Bukkit/Spigot
 - These are custom servers that support plugins but not game-changing mods. They can almost always be updated between minor versions without any issue (1.7.2 to 1.7.10) but a major update could easily break some plugins. This server type would disable automated/scripted major updates as breaking one wrong plugin can bring a server to its knees.
- Vanilla
 - This is the easiest one. Even major updates will almost never break anything (apart from making further world gen possibly look funny) so minor updates could be automatic (on startup) or at least allowed, major updates would *not* be completely automatic, (on startup) but they would be allowed after a warning and a prompt
- Forge
 - Forge supports client and server-side mods that work together to change the game with things like new blocks, mobs, world gen, and many other things. We could allow/automate minor updates (1.7.2 to 1.7.10) but completely disallow any major updates as it will *certainly* break most, if not all mods.
- Custom
 - Would have no kind of automated update system at all, but as a result would also not track anything like version numbers, so it wouldn't cause any issue if the user decided to change something on their own. (IE, it won't break itself from user tampering like others might) It would have no updating or downloading at all, just specify the JAR and what kind of parameters it needs (Like maximum RAM usage) and LGSM will simply manage starting and stopping.

**Comment by jaredballou** [comment]
This is a ball of snakes. From my experience running servers back in the 1.2 to 1.7.2 days, applying mods meant editing JAR files, and every update had the potential to break mods. So anything that supports mods then has to have a way to determine if the mods will break the server, so we have to figure that out. Whether it queries an API that it downloads mods from to see if it supports the new version, or just creating a new install and adding the mods and then doing some tests to validate that it works before updating the main server, it's going to need to be pretty complex.

I'd go so far as to say that we skip that altogether, just focus on install and control of the server, and then handle the updating and mods separately (or just support updating vanilla). It might not even work to merge to lgsm, since the games are so radically different and they need very different support structures to install and run. I'm not sure that bringing something this large into LGSM is the right move, my guess would be that you guys work on mscs separately and lift LGSM stuff that's useful to that. With all the flux in the roadmap of LGSM, it'd be a shame to integrate it into the tool and then have a major rewrite waste that effort.

**Comment by Zer0t3ch** [comment]
You don't have to edit the vanilla server JAR, (at least not by hand) you just download the installer from [here](http://files.minecraftforge.net/) which IIRC will download the vanilla server as well as its own files and then patch it automatically. While you're right, the API *can* change and break mods on minor version changes, (1.7.2 to 1.7.10) I haven't seen that happen in a long time. Every minor version update I've seen was adding features or bugfixes. Updates between major versions (1.7.10 to 1.8) will basically break all mods.

I'm not saying we need to implement updating now or anything, I was just proposing things for the future. In its current state, minor version updates with Forge are absolutely doable without issue, but I agree that it should be avoided for the most part, at least until we've got the installing and controlling working. Also, the whole possible move to Python is why I haven't written anything for this yet.

**Comment by sandain** [comment]
MSCS uses a file stored in each world's directory called 'mscs.properties' to allow each world controlled by the script to be custom configured ([see the README file](https://github.com/sandain/MinecraftServerControlScript/blob/master/README.md#server-customization) for the options available).  This is how MSCS is able to support running one world using Spigot, another with BungeeCord, another with Forge, a version 1.6.4 vanilla server, and a 1.8.4 vanilla server, all at the same time.  All the script needs to know is what .jar file to use and the URL to use when the update command is called.  Since the command to start a world server can also be placed in the .properties file, it should be technically possible to start any type of program (including a C based binary or a shell script), not just .jar based servers.  Of course, if the 'mscs.properties' file is missing, the script has default values that it uses to download and run the latest version of the vanilla server.

What MSCS does not attempt to do is deal with addons.  Since the setup process for addons can be so varied, I figured that it was simply not worth trying to add that capability to MSCS (and I don't recommend it for whatever comes out of this discussion either).

**Comment by Zer0t3ch** [comment]
@sandain I agree completely on your comment about addons/mods.

Put simply, it would be completely impractical to manage/update mods without some kind of central database existing first. (Something similar that comes to mind is CKAN for KSP) Without a database like that, adding any support for mods would simply be masochistic. 

All that said, I think it's best to avoid implementing *anything* for MC in this project until the wave of big potential changes (i.e. the move to Python) settles down.

**Comment by Scarsz** [comment]
Now that we're on the topic of Minecraft servers again

More or less, all the script needs to do is

1. Compile CraftBukkit/Spigot from BuildTools (https://www.spigotmc.org/wiki/buildtools/)
2. Have user select if they want CraftBukkit or Spigot, Spigot the better option in every way
3. Generate a `eula.txt` file with contents `eula=true`

For starting it, it would just be running the jar with normal Java, specify a command line variable in the script, default to something along the lines of

`java -Xmx8G -jar spigot.jar nogui`

- `8G` - Amount of memory in gigabytes for Java to be allowed to use
- `spigot.jar` - Server jar to run, will allow people to use custom jars like KCauldron if those aren't added to the script
- `nogui` - Force server to run headless

**Comment by cedarlug** [comment]
Agree: Use automated spigot build for deployment.
Disagree: Automatically agree to the eula -- that would certainly violate the license.
Disagree: specify fixed memory on command line
Ambivalent: nogui isn't needed anymore.

[Having just deployed 21 Spigot servers this past week.]

**Comment by Scarsz** [comment]
- You'd be agreeing to follow the EULA as with literally any other server software you install through LGSM respective of the game and it's developers
- It's a variable in the script. Variable. Change it to what you want.
- nogui doesn't hurt having when some people want to be using the vanilla jar distributed by Mojang, which needs nogui.

**Comment by dgibbs64** [comment]
Im happy to create a minecraft server that just installs vanilla for now as a base to get started. Then we can look at adding any custom servers later. After speaking with @Scarsz earlier I can see its definitely possible to use Spigot etc and there may be methods that can be used for supporting custom servers without having to manage a big database.

**Comment by cedarlug** [comment]
Again: Disagree with the license.  If the script changes it, then LGSM is agreeing to the license, not the end user.  That's a violation of the license.  Always honor the license.  The end user must change it, not the script.

**Comment by Scarsz** [comment]
You're agreeing to it by downloading and running the script. Not a hard concept to grasp.

**Comment by cedarlug** [comment]
Apparently harder to grasp than you think.

A script cannot agree to a license.

Taking your flippant approach to actual license compliance (rather than what you feel is okay), LGSM is sure to be headed toward the same fate as craftbukkit.

**Comment by Scarsz** [comment]
It's a server installation suite of Bash scripts dude, calm your shit. LGSM is intended to be a quick and easy way to install a server painlessly. For some people using it, they don't even know how text editors work. I'd much rather show a notification that the EULA is being accepted by the installer and that if you don't agree to it don't run the damn thing. I'm amazed you don't get how simple this is. It's a fucking EULA dude.

**Comment by cedarlug** [comment]
It is indeed simple.  A script cannot agree to a license.  Not hard at all. And, I don't even need to get belligerent to make my case.

**Comment by Scarsz** [comment]
Yes, because by me being "belligerent" I'm implying that I need it to make my case. Grow the fuck up dude, removing these stupid ass comments to keep the argument away from the issue.

**Comment by cedarlug** [comment]
Removing the profanity would be appropriate, but the discussion is one that should definitely be had.

**Comment by Scarsz** [comment]
License agreements aren't being broken nor is this the place to be discussing it. In any sort of situation to any degree, running a server at all under any version using any server software for Minecraft is submitting to Mojang's EULA, bottom line. End of discussion, thanks.

**Comment by igeighty** [comment]
The EULA would most assuredly be needed to be agreed by the user and not the script.
when it comes to litigation, it is the details that will bring a potential action victory.

I agree it 'seems' like a trivial proposition to have the script automatically OK the EULA, but in legal terms i can assure you it isn't this trivial.

**Comment by Scarsz** [comment]
Once again, see the above comment and the fact the user would be told that the EULA was being accepted and if they didn't want this they shouldn't run the script period. At any rate, the original development plan in my earlier comment has been edited slightly to conform to what you two feel is needed. Now, once again, please leave the license discussion out of this and leave the issue for what GitHub is for and only; development.

**Comment by cedarlug** [comment]
You use terms like "submitting" to a license, and previously (now deleted) wanted to just show a message that "the script was accepting the EULA".  These are wrong on so many levels, that the "End of discussion" has clearly not been reached on this issue.  By thinking this way, you threaten the entire project.

Just take a look at Craftbukkit - their project met their demise by the commits of one developer who didn't honor the license.

**Comment by Scarsz** [comment]
I'll be fucked if Mojang DMCA's this repository, but in reality, they won't. Nobody will be suing anyone over running a server, which, once again, is submitting to the EULA in itself. That also wasn't the reason Craftbukkit was shut down either, one developer didn't like the fact that Mojang bought it from Curse secretly and one of the developers DMCA'd for his code being in the repository.

Now, once again, any and all comments about license compliance are going to be deleted after this comment and I will delete the ones made previously in a little while. GitHub isn't a place for arguments, take it elsewhere or do the more preferred thing by dropping the very stupid subject.

**Comment by cedarlug** [comment]
Running a server is not submitting to the EULA.  That's the reason why you can't run the server until you accept the EULA, and why the license file isn't there until  you try to. 

You can delete them all you wish, at least their making their way into the inboxes of those subscribed.  

By taking down craftbukkit, hasn't it already been shown that license enforcement is taken seriously by Mojang (and now Microsoft)?  Why is violating a license by checking in  Java bytecode any different than violating an end user license agreement procedure required for the server to run?  And why would you think that one is okay but not the other?

My original assertion was that the LGSM script should not automatically script the acceptance of the EULA.  I still stand by that vehemently, and believe this **is** a discussion that should take place in this thread.

**Comment by Scarsz** [comment]
I don't care if you think this should be on this thread. It's already been amended that it'll be a user input instead of automatic; quit your bitching for fuck sake. It's a moot point and you're wasting both my and your time by dragging on this stupid argument. If you really want to cry a river about it, make a separate issue. This is the main thread for this script (even tagged with new server) thus the thread should only be about development for it. If you don't have any anything useful to say about the development of the script, don't comment. Simple as that.

**Comment by Scarsz** [comment]
Went ahead and made a strawpoll so you lot could vote on which system of EULA acceptance would be better for the script http://www.strawpoll.me/10819979

**Comment by cedarlug** [comment]
I advocate that in the development of the script that would be used to support a new Minecraft server, that in order to comply with license limitations, that the end user should be forced to accept the EULA.

That hits the "new server" topic, the "script development" for it, and a useful comment on the development of the script. 

Thanks, but I'm going to skip the straw poll.  I doubt the argument "But the poll results said we could ignore the license, your Honor" likely won't stop a take-down notice.

**Comment by UltimateByte** [comment]
https://www.youtube.com/watch?v=He82NBjJqf8

Calm down guyz, it's sunday :)

**Comment by Scarsz** [comment]
Both options result in no harm against LGSM; if anything having the user manually accept it is against LGSM's philosophy of being as user friendly as possible. Have yet to see him actually give a source on how a user input inside of the script would leave LGSM in it's absolute entirety to be DMCA'd. Funny stuff. 

If we're still recommending classics, how about https://www.youtube.com/watch?v=XsZKrctSDaw back from the ATV Offroad Fury days on the PS2

**Comment by cedarlug** [comment]
Having the user accept a license agreement goes against LGSM's philosophy?

Both options result in no harm against LGSM?  And your law degree is from?

Funny stuff?

If you want sources (will you actually read them?) start with the EULA itself:
https://account.mojang.com/documents/minecraft_eula

Then peruse the arbitration agreement here https://account.mojang.com/terms#arbitration

If you actually do read these, you would be able to identify several very viable scenarios where automating the acceptance of the EULA for someone that subsequently violates the terms of the EULA will put LGSM at risk under Mojang's "Brand and Assets" conditions (which you can read in the arbitration page).

Yes, @UltimateByte,  I am just way too serious for a Sunday night.  If given the option of being flippant or serious on licensing issues, I'll choose the latter even on a Sunday.

**Comment by Scarsz** [comment]
Seems you didn't even read it yourself. One of the first sentences, clear as day, says if they have a problem with it, they'll tell us. They're humans too, not law mongering copyright machines.

![](http://i.imgur.com/TH0xYVO.png)

Now, once again, kindly fuck off with the licensing pile of shit. It doesn't belong here. Thank you.

**Comment by cedarlug** [comment]
Yep - they'd be talking to "LGSM" rather than the server owner.

You have that exactly correct. 

All someone would have to do is name their server "Minecraft - the ultimate server for learning" (their own specific example of what they're "NOT cool with") and they'd be talking to LGSM.  Why on earth you're okay (and even advocating that) is beyond me.  

But hey, no one would ever have Minecraft in their server name deployed by LGSM, so that Mojang-LGSM conversation certainly would never happen.

**Comment by Scarsz** [comment]
You're making a moot point that's so far beyond fucking stupid I can't imagine. By your logic, Spigot should also be shut down because they're the people enabling people to break the EULA (which happens to this day, same with other server softwares). Doesn't make sense at all? Neither does your argument. Thanks for at least appearing to be letting this shitty ass argument fade.

**Comment by dgibbs64** [comment]
Yes it's my decision ultimately so don't worry about it :-)

**Comment by dgibbs64** [comment]
IM=m currently playing around with vanilla. Once this is up and running I will look at Spigot etc. Should make is easier for me once I have vanilla up and running to implement modded servers.

**Comment by dgibbs64** [comment]
made some progress with mcserver this evening. Im looking at creating the updater for mc vanilla. I can get the version from a json file https://launchermeta.mojang.com/mc/game/version_manifest.json

anyone here know of the best way to get the latest version number from it using curl?

**Comment by UltimateByte** [comment]
Found this to be working as well
curl -s https://launchermeta.mojang.com/mc/game/version_manifest.json | awk -F 'versions' '{print $1}' | awk -F '"' '{print $10}'

**Comment by sandain** [comment]
For MSCS, I went ahead and imported a real JSON package to do the work after the file format change:
```
# TYPE can be either release or snapshot
TYPE=release
VERSION=$($PERL -0777ne '
  use JSON;
  $json = decode_json ($_);
  print $json->{latest}{'$TYPE'};
' $VERSIONS_JSON)
```

**Comment by dgibbs64** [comment]
@sandain thanks I will take a look. It shoudl help me with my own implementation :D

**Comment by dgibbs64** [comment]
@sandain why is it important to compare the dates as well as the version?

**Comment by sandain** [comment]
You could just as easily write a comparison routine that works with the version id, or if the list is sorted maybe you can rely on that.  Since release and snapshot version ids use different patterns and I wasn't sure the list was sorted, I went with releaseTime to do version comparisons.  Using releaseTime makes it easy to do comparisons between release and snapshot version ids if needed without relying a separate lookup table or a sorted list.

**Comment by marvinl97** [comment]
#1024 added vanilla Mincraft support.

**Comment by UltimateByte** [comment]
Fluently ! GG !

**Comment by dgibbs64** [comment]
Its working bitches #1024. Custom servers will come in the future. Until then manually replace your jars you crazy kids!
