### ISSUE TITLE
Add Kali linux as distro option for install with steamcmd based servers

### ISSUE THREAD

**Issue by sjstein** [GameServerManagers/LinuxGSM#3359]
As it stands now, `check_deps.sh` fails when checking dependencies on Kali based distros. Kali is based on recent (stable) Debian snapshots and, as noted in the `check_deps.sh` source, has (since version 11) renamed **lib32gcc1** to **lib32gcc-s1**.

Since `etc/os-release` does not identify as debian 11, `check_deps.sh` flags a missing dependency on lib32gcc1. 

Verified things work if `/etc/os-release` is modified to "spoof" debian version 11

I'm not sure if devs are concerned with supporting offshoot variant distros like Kali; if so, I'm happy to pull source and modify to check for Kali distros

**Comment by dgibbs64** [comment]
Why would you run a game server on a pen testing distro?

**Comment by sjstein** [comment]
> Why would you run a game server on a pen testing distro?

Not sure, but it is possible. As I stated in the issue, I don't necessarily think it is a high priority issue depending on the direction they want to take LGSM. In my particular instance, I had a spare Kali machine which sits idle quite often and figured I would give it something to do.

**Comment by J-O-S-H-C** [comment]
Ok, so that is a really bad idea. Kali is designed from the ground up to be a penetration testing tool and spends very little time securing itself. It has a lot of tools pre-installed on it that can be utilized by outside individuals to compromise your system if left on all the time. Most of those tools open up ports and alter network connections to make it easier to manipulate the network. That has the adverse effect of making it easier to get hacked into.

Kali devs themselves do not recommend using it as a daily driver or even as an install. It is designed to be spun up on USB keys and not dedicated hardware. Having a spare kali install sitting idle means you have a nice little honeypot for people to gain a foothold onto your network. Now add to that a semi-public advertisement in the form of steam listing your Valheim server to anyone looking. All it takes is a simple nmap scan of your Valheim IP and anyone can see your Kali linux just sitting there.
