### ISSUE TITLE
[FEATURE] TUI(Text-based User Interface) support

### ISSUE THREAD

**Issue by AhRoon** [GameServerManagers/LinuxGSM#3400]
## User Story

You will remember my past suggestion, which was about GUI suggestion and of course it is impossible suggestion since this script mainly used for server. However, I did not know much about TUI in the past feature request, so here is suggestion: about adding TUI support. I liked the WindowsGSM-like UI, and I thought TUI version would manage the server easily than entering the command, also allows to install and manage multiple LinuxGSM instances.

## Basic info
Since it applies to all LinuxGSM, I will leave it as Any.

* **Distro:** Any
* **Game:** Any
* **Command:** None
* **LinuxGSM version:** v21.2.0

## Further Information
I liked the WindowsGSM-like UI, and I thought TUI version would manage the server easily than entering the command, also allows to install and manage multiple LinuxGSM instances.

## Feature Summary
- Add ./gameserver manager command, which opens TUI interface for easier maintenence

## Further Reading
- [Text-based user interface Wikipedia](https://en.m.wikipedia.org/wiki/Text-based_user_interface)
- [WindowsGSM](https://windowsgsm.com/)

**Comment by Claiyc** [comment]
Sounds to me like a pretty big feature that would require a **LOT** of work... It is up to the devs but I don't feel like this should be a priority for lgsm in its current state. Something like a web gui that can execute lgsm commands & perhaps interpret the output would be a much better approach in my opinion (and thats something people have already worked on / are working on)

**Comment by dgibbs64** [comment]
Since most linuxgsm commands are as simple as executing a simple command with little to no user interaction required I feel that it would do little to improve the ui experience apart from look prettier. From a development perspective, it would add significant complexity and take a long time to develop.

I webUI is something that many have requested over the years, however, is out of scope for LinuxGSM and instead would need to be its own dedicated project. There have been many who have tried to create a web ui with varying success, but I have generally seen many abandoned.
