### ISSUE TITLE
[BUG] Barotrauma: "send" command only enters the first word in its arguments

### ISSUE THREAD

**Issue by zoktiik** [GameServerManagers/LinuxGSM#3702]
## Basic info

* **Distro:** [Fedora 34]
* **Game:** [Barotrauma]
* **Command:** [Send]
* **LinuxGSM version:** [v21.4.1]

## Further Information
The "send" command doesn't seem to work well with the Barotrauma Dedicated Server, and is only able to send a single word per command. 

## To Reproduce

Steps to reproduce the behaviour:
1. Try to `send` a command with arguments, i.e. `~/btserver send say test`
2. Watch as the in-game chat shows "HOST: "
3. Check the console and see:
![](https://files.catbox.moe/q5ogmp.png)

## Expected behaviour
For "send" to allow more than one word.

**Comment by h3o66** [comment]
Well this issue is probably a issue how the command parsing is done.

Currently it should just work if you put the command between quotation marks what you want to have executed on the server console.
Example:
`./btserver send "say test"`

In this case the script just parses the second argument what is passed to it.

**Comment by zoktiik** [comment]
> Currently it should just work if you put the command between quotation marks what you want to have executed on the server console. Example: `./btserver send "say test"`

That makes sense. I had tried at least a few different combinations of the quotation marks like it's sending to a Source server (i.e. `send say "test"`) but for whatever reason I didn't think to try this one. Thank you!
