### ISSUE TITLE
My Server Wont Run

### ISSUE THREAD

**Issue by jayexe69** [GameServerManagers/LinuxGSM#3940]
My Server Cant Load A Library or something

Log is in the paste bin

https://pastebin.com/ryRzcrEG

**Comment by erdoking** [comment]
I am missing all information ...

1. game? [Log -> Rust]
2. OS [Log -> Ubuntu 22.04 64bit]
3. What do you do to start the server
4. ...

I don't see a chance to help you.

"My Server Cant Load A Library or something" 
 - And now? without any linux skills you can't host a gameserver.
 - I don't see a BUG but missing understanding how linux works ...

---
I found this errors in your log, 
```
Unable to preload the following plugins:
	libRenderer.so
Fallback handler could not load library /home/ubuntu/serverfiles/RustDedicated_Data/Mono/libRenderer
```
Is libRenderer.so existing?
find /home/ubuntu/serverfiles/ -iname libRenderer.so


`Command 'batchmode' not found`
 - it seems your start command is wrong because the parameter batchmode is get as command

`SocketException: The requested address is not valid in this context`
 - it seems your start command is wrong
 - "+server.ip" "132.145.57.233" is maybe interpreted as 
   - +server.ip=""
   - 132.145.57.233=""
