### ISSUE TITLE
[FEATURE] Possibly a Countdown for Server Shutdowns

### ISSUE THREAD

**Issue by TheEhTeam** [GameServerManagers/LinuxGSM#4063]
Would it be possible to add a preferably adjustable in game countdown timer for servers (7d2d) before server shutdowns for backups/maintenance. The shutdown is so sudden and unannounced to players in game. It can leave you in a sticky situation. Would be nice if there was a softer shutdown option that would send a server message/countdown in game giving players a x amount of time warning before shutdown.
Thank you

**Comment by Claiyc** [comment]
Would be a nice feature but very complicated to implement. Our goal would be to provide a framework that can do this for ALL gameservers but since every gameserver works different, this is not really possible. And starting to build such systems for individual gameservers would result in a huge work overload and a codebase that is very hard to manage
