### ISSUE TITLE
[Bug]: Cannot load serverlist when port is opened

### ISSUE THREAD

**Issue by Alfagun74** [GameServerManagers/LinuxGSM#4188]
### User story

As a Server Admin, I want to run a server

### Game

Garrys Mod

### Linux distro

Debian 11, Debian 10, Debian 9

### Command

command: start

### Further information

As soon as i set up a port mapping to my container, the server doesnt start with the following log.

I use caprover, which uses docker swarm and the ingress network under the hood. 

Other Issues mention the absence of curl but curl is installed. When i remove the port mapping everything works.

Portrainer Screenshot:
![image](https://user-images.githubusercontent.com/22225051/232223522-22a08921-89fa-45dc-8594-09936c4c0661.png)

### Relevant log output

```shell
2023-04-15T12:20:54.287853409Z [entrypoint.sh]starting entrypoint.sh
2023-04-15T12:20:54.288047115Z [entrypoint.sh]installing...
2023-04-15T12:21:14.357780697Z fetching GitHub serverlist.csv...ERROR
2023-04-15T12:21:34.392347863Z fetching Bitbucket serverlist.csv...FAIL
2023-04-15T12:21:34.393015728Z linuxgsm.sh: line 129: core_exit.sh: command not found
2023-04-15T12:21:34.393539877Z [ FAIL ] serverlist.csv could not be loaded.
```

**Comment by h3o66** [comment]
Not sure how we can support something like this at all on lgsm side.
At first this looks more like a network issue on your side ( as it cannot download stuff from github).

**Comment by jusito** [comment]
Because I know the image:

Is it possible to provide the logs?

Probably the container doesn't continue and sadly the logs are outside of the volume.
1. start container and overwrite the entrypoint to bash `--entrypoint bash` e.g. `docker run -it -p 27016:27016/udp -e SERVER_PORT=27016 -v TTTDebug:/home/steam/serverfiles --name "TTTDebug" --entrypoint bash --rm jusito/docker-ttt`
2. you are inside of the container with user steam, run the entrypoint with `./home/entrypoint.sh`
3. in another terminal copy the logs from outside: `docker cp TTTDebug:/home/steam/logs/ .`
4. type exit inside container, will be removed after this

**Comment by Alfagun74** [comment]
thanks man but i gave it up unfortunately and threw everything in the bin

**Comment by Fizcko** [comment]
I've got the same issue. I upgrade my docker from 19.X to 24.0.1 and this fix the problem.
