### ISSUE TITLE
[Bug]: Server hostname not displaying properly in scripts or alerts

### ISSUE THREAD

**Issue by justaFluffypanda** [GameServerManagers/LinuxGSM#4222]
### User story

As a server operator, I woud like the host name of my server be parsed correctly as to display properly in console output and discord alerts.

### Game

CS:GO

### Linux distro

Ubuntu 22.04

### Command

command: start

### Further information

Since the recent update when starting my CS:GO servers the server's name is not accurately parsed by LGSM and instead reports as "NOT SET." The "NOT SET" name also shows up on discord alerts. The server name displays correctly in-game and in gamedig queries so this is must be parsing issue within LGSM.

My Valheim server is functioning as normal, with the main difference being my CS:GO servers' names all begin with a '[' character which is possibly breaking whatever query is doing the parsing. 

![lgsm_bug1](https://github.com/GameServerManagers/LinuxGSM/assets/58008171/f53ee2cc-9cc9-46a6-8255-75ab65361a93)

![lgsm_bug2](https://github.com/GameServerManagers/LinuxGSM/assets/58008171/93c6f67d-edf6-4996-9202-8bdd875fedcd)

![lgsm_bug3](https://github.com/GameServerManagers/LinuxGSM/assets/58008171/dc67203c-227f-4f39-b70d-c719c1bd113a)

**Comment by SylenThunder** [comment]
To expand on this some, I see the same with an error in the 7 Days server.

/home/ageofdemons/lgsm/modules/**info_game.sh: line 134: -: command not found**
[  OK  ] Starting sdtdserver: NOT SET

**Comment by xRuffKez** [comment]
xmlparser won't parse if space is in sdtdserver.xml

**Comment by dgibbs64** [comment]
@xRuffKez can you provide an example of this so I can replicate it please,

**Comment by xRuffKez** [comment]
@dgibbs64 On debian11 testet:

1. Install required packets on a fresh system.
2. Download lgsm and get sdtd with cli.
3. Run sdtdserver with ai Flagge
4. Start sdtdserver

You will see an error in the cli -: Command not found.
This happens while xmlparser cannot parse spaces in strings. E.g. "Linux Gameserver". It will output NOT SET.
If you configure sdtdserver.xml with "Linux_Gameserver" or "LinuxGameserver", xmlparser successfully completes parsing.

**Comment by dgibbs64** [comment]
@xRuffKez spot on, thanks. I will look at this and add to a hotfix

**Comment by xRuffKez** [comment]
I investigated the Code and at fn_info_game_sdtd() spaces from config file sdtdserver.xml need to be escaped! Else the string won't be parsed by xmllint.

A untidy fix:
In function fn_info_game_sdtd() go under "fi" and edit the "NOT SET" to your liking.

**Comment by dgibbs64** [comment]
thanks that will help when I take a look :)

**Comment by Pshock13** [comment]
Another work around looks like you can add `&#160;` instead of spaces to the name of your server. I think this might be a healthier work around than editing "NOT SET" as it should still work just fine once this bug is fixed.

ie. instead of "My Game Host" try "My&#160;Game&#160;Host"

**Comment by Pshock13** [comment]
I've also noticed an issue with server password as well that I think is due to the use of xmllint

When ServerPassword has a **_leading character_** that cannot be escaped in XML like a dollar sign($): `value="$dollar"`
./sdtdserver dt --> `Server Password: NOT SET` & `Status: STOPPED`

When ServerPassword has a non-escapable character **_elsewhere_** in the password: `value="dol$lar"`
./sdtdserver dt --> `Server Password: dol` & `Status: STOPPED` // the $ cuts off the password 

When ServerPassword has a non-escapable **_at the end_** the password: `value="dollar$"`
./sdtdserver dt --> `Server Password: dollar$` & `Status: STOPPED` //notice the $ shows up when it's at the end but still doesn't allow the server to start up

When ServerPassword has no special characters: `value="dollar"`
./sdtdserver dt --> `Server Password: dollar` & `Status: STARTED`

I'm sure there are other characters that won't work, I only noticed this because my password previously had a leading $ before I updated LGSM and it had worked fine before.

**Comment by Ankh-** [comment]
Just a FYI, i had the same issues on my 7 days 2 Die host. Just did a check and found out that one of the dependencies got removed: libxml2-utils. Just reinstalled it and now everything works again.
The host is a LXC Debian 11 container on a Proxmox host

**Comment by dgibbs64** [comment]
I have replicated the issue with CS:GO and can confirm that anything with `[ ] ` has an issue
