### ISSUE TITLE
[Bug]: 7 Days to Die server not able to start with new ControlPanel property name syntax

### ISSUE THREAD

**Issue by bigdogpete** [GameServerManagers/LinuxGSM#4291]
### User story

Allow server to start with updated syntax

### Game

7 Days to Diec

### Linux distro

Ubuntu 22.04

### Command

command: start

### Further information

The default sdtdserver.xml had <property name="WebDashboard....".  The Web Admin console would not enable. Corrected it to the proper syntax of "ControlPanel...". Tried to start the server and it will not start but the details switch now shows the web interface is now enabled. Console log shows below. Server config files area has current syntax for the sdtd config file.

### Relevant log output

```shell
ERR Error parsing Configfile property 'ControlPanelEnabled': Unknown config option.
INF Make sure your configfile is updated the current server version!
INF Startup aborted due to the given error in server configfile
```

### Steps to reproduce

1. Open ../serverfiles/sdtdserver.xml
2. Change WebDashBoardEnabled to ControlPanelEnabled
3. Set value to true
4. Change WebDashboardPort to ControlPanelPort
5. Change WebDashboardUrl to ControlPanelPassword
6. Set value to a password.
7. ./sdtdserver start

**Comment by dgibbs64** [comment]
I have done a bunch of work related to the latest experimental branch. Butr cant remember if its merged yet

**Comment by papasha1212** [comment]
This method does not work, the same problem remains

**Comment by papasha1213** [comment]
When will you fix the problem with running this software in Docker containers on Debian OS?

**Comment by papasha1213** [comment]
The latest experimental version of version 1, and other latest experimental versions such a problem occurs that because of this nothing starts, people complain very much, I advise you to fix this, as it will lead to bad consequences, all this does not work in docker containers on a Debian system, I changed both the port and the password, I changed everything, your software is used for people who just want to play your game

**Comment by papasha1213** [comment]
11:27:11
INF CPU: AMD Ryzen 5 2600 Six-Core Processor (cores: 12)
INF RAM: 15932 MB
INF GPU: Null Device (128 MB)
INF Graphics API: NULL 1.0 [1.0] (shader level 3.0)
INF Local UTC offset: 0 hours
INF Command line arguments: /AMP/seven-days-to-die/294420/7DaysToDieServer.x86_64 -quit -batchmode -nographics -configfile=seven-days-settings-undead-legacy-experimental.xml -dedicated
INF Parsing server configfile: /AMP/seven-days-to-die/294420/7DaysToDieServer_Data/../seven-days-settings-undead-legacy-experimental.xml
ERR ====================================================================================================
ERR Error parsing configfile property 'ControlPanelEnabled': Unknown config option
INF Make sure your configfile is updated the current server version!
INF Startup aborted due to the given error in server configfile
ERR ====================================================================================================
INF UserDataFolder: /home/amp/.local/share/7DaysToDie
InvalidOperationException: GamePrefs is being accessed before it is ready.
at GamePrefs.get_Instance () [0x00007] in <6852d66f1c454f28b8c6698872258303>:0
at GamePrefs.GetObject (EnumGamePrefs _eProperty) [0x00002] in <6852d66f1c454f28b8c6698872258303>:0
at GamePrefs.GetFloat (EnumGamePrefs _eProperty) [0x00000] in <6852d66f1c454f28b8c6698872258303>:0
at SelectionBoxManager.Awake () [0x00012] in <6852d66f1c454f28b8c6698872258303>:0
Fallback handler could not load library /AMP/seven-days-to-die/294420/7DaysToDieServer_Data/MonoBleedingEdge/x86_64/`��eU/mono/aot-cache/amd64/Oxide.Common.dll.so
InvalidOperationException: GamePrefs is being accessed before it is ready.
at GamePrefs.get_Instance () [0x00007] in <6852d66f1c454f28b8c6698872258303>:0
at GamePrefs.GetObject (EnumGamePrefs _eProperty) [0x00002] in <6852d66f1c454f28b8c6698872258303>:0
at GamePrefs.GetInt (EnumGamePrefs _eProperty) [0x00000] in <6852d66f1c454f28b8c6698872258303>:0
at GameOptionsManager.ValidateFoV () [0x00000] in <6852d66f1c454f28b8c6698872258303>:0
at GameOptionsManager..cctor () [0x000d0] in <6852d66f1c454f28b8c6698872258303>:0
Rethrow as TypeInitializationException: The type initializer for 'GameOptionsManager' threw an exception.
at GUIWindowManager.Awake () [0x00018] in <6852d66f1c454f28b8c6698872258303>:0
Caught fatal signal - signo:11 code:1 errno:0 addr:0x28
Obtained 11 stack frames.
#0 0x007f48d000c050 in __sigaction
#1 0x007f48d0f3e1e7 in (Unknown)
#2 0x007f48d0e33a4b in (Unknown)
#3 0x007f48d0e303cc in (Unknown)
#4 0x007f48d0e2fe45 in (Unknown)
#5 0x007f48d0ece72f in (Unknown)
#6 0x007f48d0e1627e in (Unknown)
#7 0x007f48d106eb63 in PlayerMain(int, char**)
#8 0x007f48cfff724a in __libc_init_first
#9 0x007f48cfff7305 in __libc_start_main
#10 0x005565f55e5029 in (Unknown)

**Comment by papasha1213** [comment]
I also deleted the configs of these files in the error, nothing helps

**Comment by papasha1213** [comment]
![image](https://github.com/user-attachments/assets/c61b7bf9-392f-48ba-a2ed-a9a0144c6555)

**Comment by papasha1213** [comment]
[crash logs.txt](https://github.com/user-attachments/files/16452765/crash.logs.txt)

**Comment by karenmcd** [comment]
ya, same error when I enable it 

I even have to remove the configuration lines about the web interface completely to get the server to even start. commenting them out caused there to be syntax errors? idk?!

Once I removed it the server finally started successfully.

```
7 Days To Die Web Interface
====================================================================================
Web Interface enabled:   NOT SET
Web Interface url:       http://192.168.1.172:0/index.html
Web Interface password:  NOT SET
```
