### ISSUE TITLE
[Bug]: Some required changes for the new 'The Front' support

### ISSUE THREAD

**Issue by pharrisee** [GameServerManagers/LinuxGSM#4361]
### User story

The new 'The Front' support needs to be tweaked to fix some minor errors/misunderstandings in the current default configuration.

### Game

The Front

### Linux distro

Ubuntu 22.04

### Command

command: start

### Further information

The start script in _default.cfg needs a little tweaking:

1. The `-ServerTags` value is currently set to 'LinuxGSM', but this won't achieve what I think is expected.  The `ServerTags` options takes a prescribed set of values, see https://github.com/pharrisee/TheFrontLinuxServerInfo/tree/main#server-tags for more information about the expected values.
2. I may be mistaken about this one but current thinking on the `-ServerPassword` option is that having an empty value for it in the options stops connections to the server.  This happens because the client still asks for a password, but won't allow an empty value.
3. The default option of `-GMOverlapRatio` with a value of 2 will mean that it overrides the games default stack size and multiply it by 2.
4. The `-Game.PhysicsVehicle` option should be set to true, this fixes issues with vehicle handling in game, without this being true the vehicles have a tendency to drift like a cartoon cat and get damage when they are breathed upon.

### Relevant log output

```shell
None
```

### Steps to reproduce

This is based on the _default.cfg config file on initial setup.

**Comment by raufaser** [comment]
I want to add something to @pharrisee second point.

It is not possible to **not** set the _ServerPassword_ option. The password will always be an empty string. So the player has to enter an empty string. And the server is shown ingame as password protected.
All config values are documented [here](https://github.com/gjelsoe/TheFrontSettings/wiki/Server-Settings)

**Expected behaviour:**
It should be possible to **not** set the _ServerPassword_ option
