### ISSUE TITLE
[Server Request]: DayZ Server (223350)

### ISSUE THREAD

**Issue by LeMyst** [GameServerManagers/LinuxGSM#4501]
### Game server

DayZ Server

### Linux support

- [X] Yes

### Steam

Yes

### Steam appid

223350

### Guides

https://community.bistudio.com/wiki/DayZ:Hosting_a_Linux_Server

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by LeMyst** [comment]
DayZ Server is now Generally Available outside Experimental

**Comment by dgibbs64** [comment]
Good to know. I will just need to update the branch details etc. I should be able to release as a hotfix :)

**Comment by dgibbs64** [comment]
```
Connecting anonymously to Steam Public...OK
Waiting for client config...OK
Waiting for user info...OK
ERROR! Failed to install app '223350' (No subscription)
Failure! Validating dayzserver: : Steam account does not have a license for the required game
```
looks like the appid requires steam auth and is no anonymous. How annoying

**Comment by 0x346e3730** [comment]
Created a ticket on their tracker : https://feedback.bistudio.com/T179224

**Comment by dgibbs64** [comment]
Brilliant thanks. Logins do add an extra level of unnecessary annoyance for game servers. Hopefully they amend this soon. I am unsure if to go ahead with login added or wait a day or 2 to see if they rectify quickly.

**Comment by LeMyst** [comment]
I think you need steamauth for workshop mod. DayZ servers are most of the times modded.

**Comment by 0x346e3730** [comment]
Yeah I think it would be easier supporting authentification, the windows version did not support anonymous login since launch and I don't see any reason why they would allow it anytime soon + indeed for workshop (that is used a lot on dayz) you would require to be authenticated anyway. Are there any gameservers already working like that so I could update my PR when I have some free time ?

**Comment by skuzad25** [comment]
Wow! Good work guys. So happy this is supported, converting my server now.

**Comment by dgibbs64** [comment]
@0x346e3730 there are a few. See Killingfloor as an example. It is a shame as from what I know its a tick box settings change in there steam account somewhere

**Comment by 0x346e3730** [comment]
Updated the PR, from my understanding by looking at the bash code this is the only thing needed so that steamcmd is authenticated in all commands.
Will need to take a deeper look at the workshop integration as there is mod signing on DayZ that requires servers to add mods keys' into the servers' keys folder (see Run DayZ Server -> With Mods @ https://community.bistudio.com/wiki/DayZ:Hosting_a_Linux_Server) to work properly.
