### ISSUE TITLE
Hello, you should reconsider

### ISSUE THREAD

**Issue by Lalarian** [GameServerManagers/LinuxGSM#4614]
Hello,
Regarding this:

> 
> This is a game server command that you added manually. Its implementation depends on the game server itself and LinuxGSM doesn't have control over this. Therefore, this issue will be closed.
> 
> Ultimately, people who bought the game usually shouldn't have to turn this kind of features off, so... This is really not a priority.
> 
> That said, if you do find a way to get this command working, we can add the settings in default available config for the game, in this case, feel free to re-open with useful info.
> 

_Originally posted by @UltimateByte in https://github.com/GameServerManagers/LinuxGSM/issues/2850#issuecomment-622375636_
            

**So this basically means: No support for Linux Gamers!** 
OF COURSE we disable BattlEye for running an own private server. That's the first thing we do! Because BattlEye sucks. Your 'reasoning' honestly is ridiulous! You could as well stop all support for LinuxGSM, because a game 'could be pirated' anyway!

Honestly I was just searching for support for some specific issues, like my Ark-Client (on Linux-Steam/Proton) instantly crashing each time I enter any unofficial server **which just started after entering my own server that I am trying to setup currently using LinuxGSM hundreds of times.** Even reinstalling the client did not help.

But the amount of issues with LinuxGSM (Changing Sessions Name does not work, Changing maxplayers does not work, disabling BattlEye does not work, and that's just the beginnings.) And useless superstitious 'answers' like your's make the project look utterly useless instantly!
If you want to keep this attitude: Better go gardening instead!

**Comment by UltimateByte** [comment]
Hi,

Though I would say it differently today, I still don't think an anti cheat should be turned off by default unless it makes it impossible to play the original legit game for most players.

Most people asking for this seem to have a pirated copy of the game and it would seem wrong to openly support this, especially as far as making it default. Hence my harsh answer. (Also I was very active at the time and had to handle priorities which means I could be really way too harsh especially when a dude made a long post with no explanation just for a start parameter lol).

What do you think? Most legit players would turn anti cheat off in Ark? Still sounds odd to me.
Or is this useful only with the Linux version of the game because it breaks anti cheat ? Is it even Linux native or are you using it through Wine, Proton or else?

I'm not deciding for this anyway, but I do believe this should be discussed first.

**Comment by MicLieg** [comment]
Hi guys,
as an admin for a group of friends, I also decided to disable BattlEye on all of our private ARK servers, not because any of us is sailing the high seas, but rather because BattlEye tends to cause more problems such as lag or higher connection times than it solves (at least for our small group).

Regarding Proton, i can only point you to this thread where someone got the windows-only ASA server running with proton: https://github.com/GameServerManagers/LinuxGSM/issues/4350#issuecomment-1784045599

That your updated config parameters were not used is probably the fault of ARK itself, although ARK is very configurable, the way they implemented the game's config system seems very "special". Keep in mind that ARK overwrites the configs every time the server shuts down or restarts, so you need to stop the server before making any changes to the configs or your changes will be lost. If you really want to get a handle on the ARK configs, I recommend using [Beacon](https://github.com/thommcgrath/Beacon) as a config manager.

Also i'd like to add that there are a lot of LGSM users on Discord who are willing to help others. With LGSM issues aswell as issues that are more related to the unique issues of different games.

Github issues should focus on bugs, suggestions or improvements directly related to LGSM in my opinion.

**Comment by Lalarian** [comment]
> Hi,
> 
> Though I would say it differently today, I still don't think an anti cheat should be turned off by default unless it makes it impossible to play the original legit game for most players.

Thanks for your statement.
In my case (playing Ark on Linux using Lutris), my own server threw me out after just a few seconds, after my very first login to the vanilla server, without any configuration on top of what's needed to make it run. As I am playing with just two friends, and All these AntiCheat tools are a well known issue on Linux, my first thing was to disable it.

Of course my intention was not to whine about you being harsh, it was about showing that there are legit cases (with mine being just one mere example) for disabling this. Also btw. I am Trying to minimize the amount of needed resource load, using an old miniPC as a server, as I got average latency at best.

Generally I hope I could show a bit, that you don't need to concentrate on such things in general. I can imagine projects (like GSM) which are constantly related to commercial products (the games) are always a bit under The damocles sword, as with current legal situation one of the big publishers might consider it was time to close down whatever they don't like arbitrarily, which for sure will make people caoutios.
Thus, these publishers indirectly force non-paid people to work in their interest for no pay.

To this creates two downsides:
-LikeMic said: You need to waste your precious time by working for them (and now discussing with me ;) )
-And the use of GSM is limited, sometimes even for bigger groups, like Linux users, when it comes to anticheat software (of course it would be their job to make BattleEye work reliably in the specific case, but they don't bother)

**Comment by dgibbs64** [comment]
Im very confused about this issue. Anti-cheat is on by default as that is preferred by the developers of the game. Anti cheat can  be disabled by server admins at any time with `--NoBattlEye` I believe. So I am unsure what issue needs resolving and it looks like OP just wants to moan.
