### ISSUE TITLE
[Server Request] Rising World

### ISSUE THREAD

**Issue by spannerman79** [GameServerManagers/LinuxGSM#470]
https://steamdb.info/app/339010/
https://forum.rising-world.net/index.php/Thread/109-Hosting-a-multiplayer-game/

That I think covers as much information as I can give

**Comment by dgibbs64** [comment]
Its possible. Cannot give you an eta though. :)

**Comment by spannerman79** [comment]
No problem.  Wasn't expecting it to happen straight away.  Just thought it would be another possible server to add to your list that can run native on linux.

**Comment by UltimateByte** [comment]
Gonna check that out, after i got other stuff sorted !

**Comment by UltimateByte** [comment]
@spannerman79 I'm gonna check that out soon.
Do you own the game to give me a hand on testing ?

Strange thing is that it doesn't appear here, but maybe the list is just outdated.
https://developer.valvesoftware.com/wiki/Dedicated_Servers_List

**Comment by spannerman79** [comment]
> Do you own the game to give me a hand on testing ?

Yes I own it ([my steam profile](http://steamcommunity.com/id/spannerman79/games/?tab=all)).

From what I can understand it needs Java (I *always* install the latest stable Oracle JDK version on whatever server instance I use that needs to have Java) so perhaps script wise a check to make sure that java is actually installed? Doesn't have to install Java as different distros use different methods to install packages etc

**Comment by UltimateByte** [comment]
I sent you a steam request, so we will be able to talk about this and make tests more easily. ^^

**Comment by dgibbs64** [comment]
Why has this been closed?

**Comment by MJMPlays** [comment]
There is out of today a new version of Rising World that is fully integrated with Steam. Would it be possible to integrate it now with LinuxGSM ?

https://forum.rising-world.net/thread/7823-changelog-2018-02-14-getting-rid-of-the-hive/?postID=58188#post58188

"On linux, you can execute this command: ./steamcmd.sh +login anonymous +app_update 339010 +quit"

thanks, would love to be able to use all linuxGSM features with this server

**Comment by MJMPlays** [comment]
Hi Daniels,is there a way to use a 32bit version of steamcmd ? My computer is only 32bits where i run the RisingWorld server and so far it use to work until Steam went 64bits, so now I can't run the server anymore unless I can find a 32bit steamcmd.
Also in the linuxgsm RW server page please mention that a 64bit server is needed because Steamcmd no longer supports 32bit.thanks

**Comment by dgibbs64** [comment]
As far as I am aware SteamCMD is 32-bit only. However Rising World might be 64-bit only. Are you able to confirm this?

**Comment by MJMPlays** [comment]
Hi, nope there was a mention in steamcmd that they no longer support 32bits and now only 64bits. 

here is the log of the rwserver where the error occurs; (asks for 64bit hardware)
____________________________________________________
RW SERVER: Fatal error occurred! 
java.lang.UnsatisfiedLinkError: /home/rwserver/serverfiles/libsteam_api.so: /home/rwserver/serverfiles/libsteam_api.so: wrong ELF class: ELFCLASS64 (Possible cause: architecture word width mismatch)
    at java.lang.ClassLoader$NativeLibrary.load(Native Method)
    at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
    at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
    at java.lang.Runtime.load0(Runtime.java:809)
    at java.lang.System.load(System.java:1086)
    at t.a.a(SourceFile:129)
    at t.a.a(SourceFile:56)
    at server.i.a(SourceFile:54)
    at server.Main.h(SourceFile:559)
    at server.Main.initApplication(SourceFile:269)
    at commons.JIWApplication.initialize(SourceFile:236)
    at com.jme3.system.NullContext.initInThread(NullContext.java:87)
    at com.jme3.system.NullContext.run(NullContext.java:130)
    at java.lang.Thread.run(Thread.java:748)
Also the developper of Rising world (Red51 did a mention of it on this thread (https://forum.rising-world.net/thread/7816-so-how-to-install-steam-on-linux-to-make-the-new-server-run-now/ ) , here is the mention;   
==========
  

red51  
      Developer      
- Likes Received
- 121
- Posts
- 5,579
- 16
   Feb 15th 2018      Hmm... I'm sorry but I just found out that 32 bit Linux isn't supported anymore  The Steam API wrapper we're using dropped support for 32 bit Linux recently... unfortunately we cannot switch to an older version. I'm so sorry that I didn't realize that before, otherwise I would have informed you about that issue   ===================

**Comment by dgibbs64** [comment]
Do you have a link about steamcmd being only 64-bit now. If so I will need to alter documentation. If Valve are only supporting 64-bit now there is not a lot I will be able to do

**Comment by MJMPlays** [comment]
Hi,It was Red51 (developer of Rising world) that mention it in a thread on his forums, I sent you the reference in the previous email. you may want to check with him directly. It's important to let everyone know that it no longer works on 32bits systems.

The game worked all ok until the developer went to Steam and started to use the steam api's , then my 32bit hw server no longer wants to start due to an incorrect architecture for the libsteam_api.so that is just supporting now 64 bits systems :(thanks

**Comment by dgibbs64** [comment]
Sorry missed that bit.  So what Red51 is saying is Rising World server is now 64-bit only now because the Steam API wrapper they are using for the game is 64-bit only. This will be built in to the game and not related to SteamCMD.

So there is nothing I can do about this as its related to Rising World development. I will however update documentation to reflect that Rising World server only supports 64-bit.

I recommend upgrading to a 64-bit OS as all CPU's for around the past 10 years have supported 64-bit. I dont think there is any reason to use 32-bit distos anymore and 64-bit is backwards compatible anyway. In fact many distros have/are discontinuing 32-bit versions. https://www.omgubuntu.co.uk/2017/09/ubuntu-17-10-32-bit-builds-dropped

**Comment by MJMPlays** [comment]
Hi Daniel,thanks for the reply, I've manage to re-install Linux Mint in 64bits on my server and now the game and your scripts  work wonderfully !
So I can confirm that it needs the 64bit OS to run the RW server as the api lib is only for 64bits OS's and will not run on 32bits ones.
On a side note, I was wondering if it's possible in the near future to have a graphical interface for the options of your scripts, maybe even included with the Rcon (console) of RW server. It would be amazing to have all the commands in one place.
Thanks a bunch again for making the scripts working with RW server.
Jorge

**Comment by dgibbs64** [comment]
@MJMPlays well there are no plans for a graphical interface (for various reasons) a few have attempted a web interface but nothing that is "production ready". However I have been talking with a company that are creating a HLSW replacement. Its not ready yet but I have been given a preview and its awesome! I think it will compliment LinuxGSM perfectly.

https://www.obek.com/
