### ISSUE TITLE
Feature Request: ARK update mods functionality

### ISSUE THREAD

**Issue by Pr0gmanHC** [GameServerManagers/LinuxGSM#547]
Hey, 

I like this server manager very much, using the LGSM for some server, including ARK. I'm wondering if it would be possible to implement a feature in the arkserver script to also update mods. For example like the guys did for the Linux Ark Server, they added a sub-argument to their update routine called --update-mods.

This would be very useful as currently I'm working on a manual basis and update the files via SFTP when they was updated. This is very slow and only possible when I'm at home. Also thinking of using the Linux Ark Server Tools instead of LGSM for ARK, but all servers I'm using are managed by LGSM, so - I would like to have this implemented rather than change the whole server manager. :)

Thanks!

**Comment by dgibbs64** [comment]
It is certainly possible. However my current issue is time...which is currently limited. I would like to add this functionality but because I look after scripts for around 30 different servers its quite difficult to get time to implement. I do however fully welcome anyone to develop this feature and am happy to merge this. If this cannot be done I will certainly look to add this in but that may take a while.

**Comment by DarthDestroyer** [comment]
Maybe, i could provide some Ideas... But im not so good at bash...

the download from steam isnt that hard! => workshop_download_item 346110 572277026 validate

the decompression is - for me as not basher - a little bit to high!
look what they did => https://github.com/FezVrasta/ark-server-tools/blob/master/tools/arkmanager#L1264

**Comment by UltimateByte** [comment]
Closing, let's discuss here : https://github.com/GameServerManagers/LinuxGSM/issues/802
