### ISSUE TITLE
Fix : Error script.log No such file or Directory

### ISSUE THREAD

**Issue by PhilPhonic** [GameServerManagers/LinuxGSM#646]
Hi,
when I install ArmA 3, following error occurs:

> [...]
> # Installing SteamCMD
> 
> ```
> fetching functions/check_steamcmd.sh...OK
> ```
> 
> [ WARN ] SteamCMD is missing
> /home/a3/functions/core_messages.sh: line 14: /home/a3/log/script/arma3-server-script.log: No such file or directory

I think it's not important, I just wanted to report it.

**Comment by UltimateByte** [comment]
Those errors are harmless informations, as it should download steamcmd and and create this folder. Can you confirm that it worked well for you ?

BTW, thanks for your feedback. ;)
Maybe making it look less like an error would be better for user comprehension.

**Comment by PhilPhonic** [comment]
Yep, installation worked just fine ;-)

**Comment by UltimateByte** [comment]
So it'd just be about improving displayed messaged so those errors don't seem like they're real errors ?

**Comment by PhilPhonic** [comment]
Yes, sir. I think it could confuse people, like it confused me ;-)

**Comment by UltimateByte** [comment]
Well, i'll see what i can do about this, we have some predefined codes to dispkay text, i could add some, thx for informing us btw !

**Comment by UltimateByte** [comment]
@dgibbs64 
https://github.com/dgibbs64/linuxgsm/blob/master/functions/command_install.sh
-> Could just the the fact that "install_logs.sh" comes a bit too late to the party > should be before installers, that use logs. If you think this is it, can you just put it before in the code ? Like between check.sh and install_header.sh ?

Reason why i think it happens : install_steamcmd.sh calls check_steamcmd.sh, that himself tries to write stuff to the script log files that isn't created yet.


Functions to check otherwise : 
https://github.com/dgibbs64/linuxgsm/blob/master/functions/install_logs.sh
https://github.com/dgibbs64/linuxgsm/blob/master/functions/install_steamcmd.sh
https://github.com/dgibbs64/linuxgsm/blob/master/functions/check_steamcmd.sh
https://github.com/dgibbs64/linuxgsm/blob/master/functions/check.sh
https://github.com/dgibbs64/linuxgsm/blob/master/functions/check_logs.sh

**Comment by dgibbs64** [comment]
Yup I know about this and why it appeared. It will be an easy fix

**Comment by UltimateByte** [comment]
@dgibbs64  Was that simple ? Really ? :o))
