### ISSUE TITLE
[sbserver] needs code to select 32 or 64-bit version

### ISSUE THREAD

**Issue by dgibbs64** [GameServerManagers/LinuxGSM#752]

**Comment by UltimateByte** [comment]
Manual or automatic ?
(Manual could be that)
https://github.com/dgibbs64/linuxgsm/blob/master/Hurtworld/hwserver#L44
https://github.com/dgibbs64/linuxgsm/blob/master/Hurtworld/hwserver#L75

**Comment by marvinl97** [comment]
Not longer relevant. Since 1.0 there is only x86-64:

`starbound_server: ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, stripped`

The directories "linux32" and "linux64" aren't there anymore. Only "linux".

Source: http://community.playstarbound.com/threads/where-are-linux32-binaries.119040/

**Comment by UltimateByte** [comment]
Good job. :)
