### ISSUE TITLE
ubuntu dpkg --add-architecture i386 required

### ISSUE THREAD

**Issue by Aftek** [GameServerManagers/LinuxGSM#771]
With a fresh new LXC container of Ubuntu Trusty amd64,
`lxc-create -n container_name -t download -- -d ubuntu -r trusty -amd64`

I was getting the following errors about libstdc++6:
`E: Unable to locate package libstdc++6`
`E: Couldn't find any package by regex 'libstdc++6'`

Yet it was working on the host system which is also Ubuntu Trusty amd64;

Found my answer at https://akrabat.com/installing-32-bit-packages-on-ubuntu-14-04/
`dpkg --add-architecture i386` was needed;
and then I realised it is part of the Debian 64bit dependencies that can be seen on your home page.

The issue can actually be considered resolved already.

but since running `dpkg --add-architecture i386` does not create a duplicate when ran multiple times;
I'd only suggest adding it to the Ubuntu dependencies too;

**Comment by UltimateByte** [comment]
So the LXC container has nothing to do with that ? I'll rename that issue :)
What version of ubuntu are you using ? 14..4 ?
Thanks for your help btw.
@dgibbs64 :)

**Comment by cH40z-Lord** [comment]
Having the same issues on an Ubuntu 14.04 LTS AMD64 and 16.04 AMD64.

However, it seems to be an issues with a more recent (as in ~6 months) change since I've freshly installed a Teamspeak 3 Server just fine without getting the message about a missing libstdc++6 installation over and over again.

The fun thing is that the packages are already installed that are mentioned here: https://github.com/dgibbs64/linuxgsm/blob/master/functions/check_deps.sh#L133

Not sure if it's important but my LGSM version dates back to 040715.

If you need any additional information feel free to ask. I'd be honored in helping you fixing this problem.

**Comment by UltimateByte** [comment]
The way LGSM checks for installed packages may not be suitable for people using containers. LGSM has never been designed for that.
As i'm personally not using containers, and can't spend the required time on it to hopefully fix this, i'd need somebody to understand what's wrong so we can have a chance to fix it.

**Comment by cH40z-Lord** [comment]
I'm not using containers at all. It's a pure Ubuntu 14.04 and 16.04 LTS image directly downloaded from Canonical.

Though the steps in the link you mentioned are working I still find it not optimal. The crucial thing that is missing from what LGSM currently is doing is a simple `sudo apt-get update` after the foreign architecture has been added to make it work. However, do we really wanna do something like this or is there an alternative approach to this? Unfortunately my Linux skills in this regards are somewhat limited but maybe someone else can jump in to help?

**Comment by UltimateByte** [comment]
Oh well i thought that was another issue with containers. My bad.

dpkg --add-architecture i386; apt-get update

Yep it is written in that order onto the website and must be performed as such in order to work, as the --add-architecture changes available packages.

So in the end @dgibbs64 would be great to add "dpkg --add-architecture i386" to Ubuntu requirements as it doesn't create duplicates and might help some people. :)

**Comment by Aftek** [comment]
sorry, this was really only a suggestion, `dpkg --add-architecture i386` fixed my issue for that and was mentionned for debian based system so not too hard to figure out either.

for the other container issue, i'll take another look not too far in the future and let you know what i found or where i'm stuck there ( probably with the new LTS 16.04 too ).

**Comment by UltimateByte** [comment]
Don't be sorry, you're right, there seems to have some cases where this is necessary on Ubuntu, so i guess we should update the dependencies. :)

Any help for containers support would be appreciated as i didn't experiment LGSM with it (and i think it's the same for Daniel). But container support is really secondary, especially for now, as Daniel is preparing a wonderful update. ^^

**Comment by UltimateByte** [comment]
One more similar issue http://steamcommunity.com/groups/linuxgsm/discussions/0/359547436752843687/

@dgibbs64 
I think you really need to add this to Ubuntu dependencies
`dpkg --add-architecture i386; apt-get update`

**Comment by dgibbs64** [comment]
Done

**Comment by UltimateByte** [comment]
Thanks @dgibbs64 ! :dancer:
