### ISSUE TITLE
[Website] CSS broken/missing for Teamspeak 3 installation

### ISSUE THREAD

**Issue by keichinger** [GameServerManagers/LinuxGSM#803]
Browsing https://gameservermanagers.com/lgsm/ts3server/ shows a broken site without any CSS from time to time.

Sometimes it's working, sometimes it's not. Maybe it's an issue with your Reverse Proxy (CloudFlare)?

**Comment by UltimateByte** [comment]
Same for me. 

Guess @dgibbs64 uses cloudflare, maybe the reason for that.

**Comment by cH40z-Lord** [comment]
Yeah, pretty sure he does since the SSL certificate is also a CloudFare one. Btw there are also numerous HTTP vs. HTTPS errors inside the developer console. As a rule of thumb: If a specific resource is available via HTTPs then always use that address instead of hacks like `://domain.tld/path` (yes, the missing `http` or `https` at the beginning is on purpose to make the browser use the current protocol) to prevent errors like this in the future :)

**Comment by UltimateByte** [comment]
Screenshot : 
http://image.noelshack.com/fichiers/2016/17/1462138935-gamesmanager-error.png

**Comment by AlexCSilva** [comment]
I noticed this too, happened on GMod page but rest were fine

**Comment by dgibbs64** [comment]
Hmmm need to have another look. I might even disable SSL for now. Only enabled it as it's now recommended to have SSL on.

**Comment by cH40z-Lord** [comment]
Why do you need/want to disable SSL?

**Comment by UltimateByte** [comment]
TLS (new name for SSL) prevents you from getting your data stolen or worse, compromised between the server and the user. Risks are low, but it's still cool. :)

**Comment by dgibbs64** [comment]
yeah google recommends it is turned on. Apparently also helps with page ranks. I am trying to get TLS working correctly.

I am looking at this right now to try and see if I can get it working

**Comment by UltimateByte** [comment]
I recently used let'sencrypt script for apache2 recently, and i'ts been working flawlessly. It changed my Vhosts files a bit, but tweaked it right for HTTPS redirection. However, i didn't renew certificates yet (every 3 months), i don't know how it's gonna be done yet. :o))

**Comment by dgibbs64** [comment]
Hopefully fixed it now. It was mainly just forgot to change some content from http to https. I picked cloudflare as I was already using it and it was pretty painless. Please test an let me know if you find any more issues

**Comment by cH40z-Lord** [comment]
The Teamspeak-Site is fixed, though the Mainpage and for example Starbound are broken.

![image](https://cloud.githubusercontent.com/assets/439899/14951780/d3b447c8-105b-11e6-9f12-5a5ba3d54861.png)

**Comment by UltimateByte** [comment]
Broken for me too. There are non-HTTPS elements loaded on the page.. Not sure if it's related though.

**Comment by dgibbs64** [comment]
thanks I will keep hunting these down :)

**Comment by UltimateByte** [comment]
Your issue seems to bee that CSS isn't loading for some reason.

Concerning non HTTPS elements, i had this issue with gametracker not providing HTTPS server banners.
That way that page of mine is not full HTTPS for example : https://www.terageek.org/servers/
In chrome the "https://" stops being green on pages with anything non https, even if it's only images. Kinda boring.

**Comment by dgibbs64** [comment]
I think this is fixed now. Closing
