### ISSUE TITLE
[all mods] use yaml file to configure server

### ISSUE THREAD

**Issue by 42antoine** [GameServerManagers/LinuxGSM#903]
Because i am a little be in pain when i update the server main file ([like this one](https://github.com/dgibbs64/linuxgsm/blob/master/CounterStrikeSource/cssserver))

I request the availability to manage configuration from a yaml file, or whatever else but an external file.
- seems better to update
- seems better to generate new server

**Comment by jaredballou** [comment]
Take a look at my fork, which creates a ~/lgsm/servers/cssserver/cfg directory with Bash config files. I haven't been keeping it up to date with upstream, and I haven't worked on it in a month or so. I haven't tried CSS, I only tested with Insurgency, but if you want to give that a try I'd be glad to help you get it working.

If none of that scares you, download the lgsm-core script (directions in the README) and give it a shot. It also uses my gamedata structure, so instead of creating a complete separate script for each game, I was supporting them via small addon scripts off the core.

As far as next gen, I am working on https://github.com/jaredballou/lgsm-python which is a complete ground-up rebuild using the gamedata design in Python. All configs will be in YAML or JSON format, it'll have a lot of menu driven features, and generally be more reliable than relying on Bash to interpret text.

If you want to throw out other ideas and suggestions for the next gen tool, I'm all ears.

**Comment by UltimateByte** [comment]
That's something we have in mind since a while btw, but didn't figure out how to implement in a way that makes sense for lgsm yet. There might be a way with jaredballou's work but as my python lvl is 0 i can't be any help here. :)

**Comment by dgibbs64** [comment]
Something like that is planned eventually when the time is right.  However it's gunna take time. Although python was considered I simply do not have the time to rework several years worth of work.

**Comment by 42antoine** [comment]
I will try to propose something in few weeks, limited to my own needs (teamspeak, css, csgo servers).

I am thinking about something like this https://gist.github.com/epiloque/8cf512c6d64641bde388, so a parser without need to third party tools.

**Comment by JimTR** [comment]
Just connect to a database and throw the config in there everything in an array

**Comment by 42antoine** [comment]
Here, a very basic example and a beginning of advancement on what I could (if you like) propose.

- [csgoserver_test](https://github.com/42antoine/LinuxGSM/blob/master/CounterStrikeGlobalOffensive/csgoserver_test) : the csgo installer test file; look at the "exit;" at the bottom of file, like this only the yaml parsing is executed.

- [config.yml](https://github.com/42antoine/LinuxGSM/blob/master/CounterStrikeGlobalOffensive/config.yml) : a simple example of config file

- new or edited files : lgsm/functions/core_yaml.sh & lgsm/functions/core_functions.sh
       - [commit 1](https://github.com/42antoine/LinuxGSM/commit/c55e97d28113c193965f8f1cb1b3466f0268532e)
       - [commit 2](https://github.com/42antoine/LinuxGSM/commit/d33a069abdfd5d9c34d54fb70d863b78c16b3303)

- [Based on this code](https://gist.github.com/pkuczynski/8665367)

Nothing yet to propose a pull request. What do you think of this piece of code? I continue ?

**Comment by togenshi** [comment]
Fyi I have the following on top of my csgocomp:
hostname="\"\\\"RFLAN PLE CS:GO - BRACKET A - Match Server #1\\\"\""
password="password"
wm_save_dir="rflan"

Parameters:

fn_parms(){
parms="-game csgo -usercon -strictportbind -port ${port} +clientport ${clientport} +tv_port ${sourcetvport} +sv_setsteamaccount ${gslt} -tickrate ${tickrate} +map ${defaultmap} +servercfgfile ${servercfg} -maxplayers_override ${maxplayers} +mapgroup ${mapgroup} +game_mode ${gamemode} +game_type ${gametype} +host_workshop_collection ${ws_collection_id} +workshop_start_map ${ws_start_map} -authkey ${authkey} _**+hostname "$hostname" +sv_password ${password} +wm_save_dir ${wm_save_dir}"**_

You could pass the arguments in for any custom variables such as team names.  

The issue I have is escaping the quotes and spaces. But it seems prefixing "\"\\\" and postfixing \\\"\"" the variable works from within the script. 

I am all for introducing a separate config file for start up paramaters/gslt/api tokens but I do not believe that YAML is the good choice.

**Comment by dgibbs64** [comment]
I have previously looked in to yaml and I don't believe it will fit well with bash. There was a recent major update that separates config files from the main script that was chosen.
