### ISSUE TITLE
Gmod: Steam API fail please help

### ISSUE THREAD

**Issue by vingard** [GameServerManagers/LinuxGSM#929]
Infomation:
http://imgur.com/a/T3vPB

Please help.

**Comment by UltimateByte** [comment]
1) Hi anyways
2) I'd worry first about the wrong convars you set
3) I'd provide some information if i wanted help
4) I'd post the issue in the appropriate place. Support for issues happening because of what's between the desk and the chair happens here : https://steamcommunity.com/groups/linuxgsm/discussions
3) The Steam API failed is a non error https://github.com/dgibbs64/linuxgsm/wiki/FAQ#s_api-fail-steamapi_init-failed-steamapi_issteamrunning-failed
4) What game are you even talking about ?
5) Why don't i see any output of `./gameserver details` ?

Please, go and post into the steam group, and provide some relevant information.

**Comment by TheVingard** [comment]
Sorry.

**Comment by UltimateByte** [comment]
No problem.
Please, make sure you read this before posting into the steam group, it'll help you giving relevant information : https://steamcommunity.com/groups/linuxgsm/discussions/0/458604254471755996/

**Comment by UltimateByte** [comment]
Closing, as duplicate from http://steamcommunity.com/groups/linuxgsm/discussions/0/359543951714109227/
