### ISSUE TITLE
Enforce .cfg settings through "gameserver"

### ISSUE THREAD

**Issue by UltimateByte** [GameServerManagers/LinuxGSM#972]
Just thought it'd be cool to be able to enforce some settings through the "gameserver" script itself. LGSM could then write to the cfg (or other) file, if found, upon start, and otherwise warn the user that the file isn't found or if the parameter doesn't exist into the config file.

I'm thinking about two main things : 
- Servername/hostname
- RCON Password

Could also be used for icecast if we find out we can release it (that's how i actually got the idea).

What do you think ?

**Comment by jaredballou** [comment]
In my Python fork, I have a ConfigParser wrapper that supports srcds-style cfg files. My thinking is that we would push certain settings from the LGSM config (hostname and password, but there are a lot of other settings that would work for. Ideally, I want to have all managed config settings for the server in the gamedata configs. The script would ensure that all desired settings get placed into server configs as needed, so that we handle things more gracefully than pushing a flat file and munging it.

**Comment by UltimateByte** [comment]
Well, RCON password is now randomly set... And hostname and more globally, settings are better off set within config file directly. Wether users change config within their gameserver script or config file doesn't really matter since users should go edit their config files anyways. Having all settings within gameserver script seems like a counter productive task to do, so i'll just close this.
