### ISSUE TITLE
Supplying default "Y" -> answering "yn" means "y"

### ISSUE THREAD

**Issue by TamaHobbit** [GameServerManagers/LinuxGSM#997]
The normal convention for commandline tools is to ask "Y/n", and you have to enter either Y or n. It seems that LGSM supplies y already, meaning you only have to press enter. However, a new user can easily overlook this, reading "was the install successful ..." I don't even look to see that y is already filled in for me, as my eye skips over the pattern [Y/n]. A fix would be to add, say, 4 spaces after ] and before the "y" that is my default answer.

The result when I look back is that LGSM accepted this:

`Was the install successful? [Y/n]yn`

to mean "yes". So another fix I would suggest is to check for that answer and make that mean "n", or to make it request clarfication if the answer is not "y" or "n".

**Comment by jaredballou** [comment]
My take here is that the whole user input thing needs to be refactored. There ought to be a new function for user input, which will let us better handle errors and conditions in a central location, rather than needing to validate and mess with each separate value. I've been batting around an idea for handling input which I will post as a new issue presently.

**Comment by UltimateByte** [comment]
Interesting remark from @s-eam 

> The Y/N prompts can be different in certain aspects (e.g., character case, spacing, and initial text) than those found in other CLI programs. This difference may make LGSM less intuitive for new users.

For my part, i'd love to see some standardized prompts in core_messages.sh.

**Comment by dgibbs64** [comment]
a standard prompt has now been created and is in the develop branch ready for next release
